### ISSUE TITLE
How to downgrade with kernver 3?

### ISSUE THREAD

**Issue by LavedenC1** [ading2210/shimboot#100]
My kernver is 0x0000003 (idk how many zeros but it ends with the number 3). I want to downgrade to use an exaploit to get access to crosh. Can someone help me?

On chrome os 126. Managed. Devmode blocked, sh1mmer doesnt work.

**Comment by ading2210** [comment]
If you use an old enough recovery image (like v107), and use devmode while recovering, it will ignore the downgrade check.

**Comment by LavedenC1** [comment]
thanks!
