### ISSUE TITLE
Umm I installed shimboot on an drive I wanted to keep but now I cant get rid of it help pls

### ISSUE THREAD

**Issue by githubmaster8899** [ading2210/shimboot#101]
any suggestions please help pls!

**Comment by githubmaster8899** [comment]
i cant beacuse my pc wont dectect it when i plug it in

**Comment by Raf128** [comment]
Can you go to disk management and see if it appears there?

**Comment by ading2210** [comment]
Are you sure your drive isn't dead? 

Also this isn't a bug with shimboot.

**Comment by Fighterhen63** [comment]
@githubmaster8899 Go to the chrome recovery tool and press the cog at the top right and erase the drive if it shows up in the list of devices to erase. If it does not show up here try using an adapter to see if anything shows up. If this works then just use the same method I listed above. If it does not show up at all it might be dead or broken.
