### ISSUE TITLE
Steam not downloading

### ISSUE THREAD

**Issue by Nightkillerboi** [ading2210/shimboot#102]
Every time i try to install steam using scripts it says E: Package ‘steam’ has no installation candidate
![Uploading image.jpg…]()

**Comment by ading2210** [comment]
Your image did not get uploaded. Also, please don't delete the issue template that asks for additional information.

**Comment by Fighterhen63** [comment]
@Nightkillerboi Try sudo apt update && sudo apt upgrade then try sudo apt install steam then once you open it if you get an error run fix_bwrap

**Comment by ading2210** [comment]
This is the same problem as #110. The OP is using an ARM Chromebook so Steam can't run natively.
