### ISSUE TITLE
Linux-enviroment not enabling. 

### ISSUE THREAD

**Issue by Kalelalhabi** [ading2210/shimboot#105]
So i booted chrome os without enterprise enrollment, but when i tried to enable linux enviroment it said that virtual machine failed to load. Google play store didnt open either. Idk if im just stupid or these arent yet supported

**Comment by OtterCodes101** [comment]
shim kernel probably doesn't support kvm

**Comment by ading2210** [comment]
This is the same issue as #51. You probably need to downgrade your Chrome OS version.
