### ISSUE TITLE
Play Store Doesnt work with error code 7.

### ISSUE THREAD

**Issue by zxc-mrt1n-o4** [ading2210/shimboot#107]
**Describe the bug**
Then you booting ChromeOS from USB (no matter A or B) it will try to load play store services and after some time give error code 7. I completely don't understand why its happens.

**To Reproduce**
1. Go to ChromeOS_ROOT_A/ROOT_B'
2. Create/Login Into Account.
3. Try to open Play Store

**Expected behavior**
Use Play Store normally

**Screenshots / Photos**
![image](https://github.com/user-attachments/assets/05347242-86ff-49c0-ac77-27b3d7113372)

**Target Chrome OS Device (please complete the following information):**
 - Board Name: corsola (yea sound don't works)
 - Device Name: steelix
 - Shimboot version: 1.2.1

**Comment by zxc-mrt1n-o4** [comment]
![image](https://github.com/user-attachments/assets/2258d582-7ca2-4318-a795-3ee3d1ecef26)

**Comment by ading2210** [comment]
This is a duplicate of #51.
