### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by WeirdPerson420** [ading2210/shimboot#11]
When I'm on the shimboot bootloader screen i choose default then it sits on a black screen with a mouse cursor forever

**Comment by OtterCodes101** [comment]
maybe try redownloading shimboot?

**Comment by WeirdPerson420** [comment]
Didn't work :/

**Comment by WeirdPerson420** [comment]
Read: 104.59 MB/s
Write: 28.98 MB/s

**Comment by ading2210** [comment]
Which board do you have and which prebuilt image did you use?

**Comment by WeirdPerson420** [comment]
According to the chrome it's a grunt motherboard so i used the grunt prebuilt. It also says careena in recovery mode

**Comment by WeirdPerson420** [comment]
I fixed it!
I compiled it from source rather than using a prebuilt and now it works.
