### ISSUE TITLE
Steam still isn’t downloading

### ISSUE THREAD

**Issue by Nightkillerboi** [ading2210/shimboot#110]
This is what it’s been telling me for the past week. (PLEASE HELP ME😭)
![image](https://github.com/user-attachments/assets/33b24136-7cf3-45ed-bf85-03e26fcda781)
![image](https://github.com/user-attachments/assets/c0f6fda7-2771-40f9-9f5f-b7c854f9be0a)
![image](https://github.com/user-attachments/assets/c814228f-ab16-45e3-8d7e-6270a9dba0fe)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Photos**
If applicable, add screenshots or photos to help explain your problem.

If you are reporting an issue with the build process, please run the scripts in debug mode by putting `DEBUG=1` before the build commmand, like `sudo DEBUG=1 ./build_complete.sh`.

**Target Chrome OS Device (please complete the following information):**
 - Board Name (e.g. dedede)
 - Device Name (e.g. drawcia) 
 - Shimboot version (e.g. v1.0.1) 

**Build Device (please complete the following information):**
 - OS: [e.g. Debian 12]
 - Neofetch out [run `neofetch --stdout` and paste it here]

**Additional context**

**Comment by Nightkillerboi** [comment]
How do i use steam installer int he debian repository?

**Comment by OtterCodes101** [comment]
`sudo apt install steam`

**Comment by Nightkillerboi** [comment]
I installed it a second ago what do i do now?![image](https://github.com/user-attachments/assets/f35017f7-9b7f-4aac-b116-f6527b96eee4)

**Comment by OtterCodes101** [comment]
shit i think the deb version is still somewhat installed
do sudo apt remove steam then try it again

**Comment by Nightkillerboi** [comment]
Alright did that. Is there any third party opener i gotta use?
![image](https://github.com/user-attachments/assets/69cf0549-ea2b-484c-aa12-1b94eb515ab7)

**Comment by Raf128** [comment]
you did fix_bwrap?

**Comment by ading2210** [comment]
@Nightkillerboi Jacuzzi boards have an ARM CPU. Steam is x86 so it will not run natively. You have to install an emulator like [box86](https://github.com/ptitSeb/box86)/[box64](https://github.com/ptitSeb/box64) for it to work. While it is possible, I can't provide support for this since I don't own a ARM Chromeboook.
