### ISSUE TITLE
Can't access recovery mode - Octopus board/Version 128 enrolled

### ISSUE THREAD

**Issue by thankthehokeman** [ading2210/shimboot#111]
Specifications:
Dell Chromebook 3100
Board Name: Octopus
Device Name: Fleex version 128.0.6613.163. Platform 15964.59.0
Developer Mode: Disabled
So I was able to create my bootloader for the Octopus and I cannot enter recovery mode at all despite using the escape+refresh+power combo at the same time even when signed out. I am unsure of what to do from here onwards. I also do not want to tamper with the enrolled software unless it's a last resort. Is there anything at all I can do or should I just give up and wait?

![IMG_3400](https://github.com/user-attachments/assets/1f0b15c7-94ff-4e6e-a119-7706ac864edc)

**Comment by ading2210** [comment]
You have to enable developer mode, which requires a powerwash. Otherwise it is not possible.

**Comment by thankthehokeman** [comment]
oh gotcha. Thanks anyways
