### ISSUE TITLE
Booting With an SSD

### ISSUE THREAD

**Issue by NikhilKonduru8** [ading2210/shimboot#115]
I am trying to boot with a SSD rather an USB drive, but after getting into the menu and choosing 3 to boot from the ssd drive nothing is showing up on the screen even after watiting for a while.

**Comment by ading2210** [comment]
Please do not delete the issue template which asks for more information.

**Comment by NikhilKonduru8** [comment]
Also when I try to run "sudo ./build_complete.sh hatch desktop=kde" in the terminal it says: "sudo: ./build_complete.sh: command not found"

**Comment by NikhilKonduru8** [comment]
> Please do not delete the issue template which asks for more information.

sorry

**Comment by Fighterhen63** [comment]
@NikhilKonduru8 Make sure you run git clone https://github.com/ading2210/shimboot.git then cd shimboot (or whatever the folder is called) then run sudo ./build_complete.sh hatch desktop=kde

**Comment by NikhilKonduru8** [comment]
Thank you! But booting with an SSD is still not working. Do you have any suggestions?

**Comment by ading2210** [comment]
Does booting with a regular USB drive work though?

**Comment by NikhilKonduru8** [comment]
yes, but Its only 64gb
