### ISSUE TITLE
Charging

### ISSUE THREAD

**Issue by NikhilKonduru8** [ading2210/shimboot#118]
The battery keeps saying charging and discharging.

**Comment by ading2210** [comment]
You keep on deleting the issue template that asks for more information. Please don't do that.

Anyways, it's a known issue that charging is slow in shims. The workaround is to plug in the device when it's powered off, and then boot up shimboot. This way, the charging isn't slow as you are using it.

**Comment by NikhilKonduru8** [comment]
> You keep on deleting the issue template that asks for more information. Please don't do that.
> 
> Anyways, it's a known issue that charging is slow in shims. The workaround is to plug in the device when it's powered off, and then boot up shimboot. This way, the charging isn't slow as you are using it.

What do you mean by deleting the issue template

**Comment by solanuscasey** [comment]
when you make a report, there is a template it asks you to fill out. if you don't plan on filling out the template then make a blank issue using the blue hyperlink at the bottom of the selection page.
![Screenshot 2024-10-14 18 11 27](https://github.com/user-attachments/assets/af91e655-8345-42f0-a756-07efa652dbc3)
