### ISSUE TITLE
Updating to Modern Linux Versions

### ISSUE THREAD

**Issue by solanuscasey** [ading2210/shimboot#119]
Probably already answered, but is there a way to update the already installed shimboot to a newer/standard Linux version? Some programs I would like to run will be removing support for Ubuntu versions before 19 or 20. This is not urgent and I will keep trying to get it working, but if you have resources to help me out that would be fantastic. Thank you for your time.

**Comment by ading2210** [comment]
Shimboot uses Debian 12 (released June 2023), which is already a modern distro.

**Comment by solanuscasey** [comment]
interesting, I know that this is on debian 12, but I am getting this error message whenever booting a program up. 

You will continue to receive updates until March of 2025. After this time, you will no longer receive updates or support for Launcher, and we recommend that you move to a newer version of Linux (Ubuntu 20.04+) to continue receiving future updates. You will still be able to use the Launcher for older versions of Linux (Ubuntu 19.04 and older) devices without support or updates.

**Comment by solanuscasey** [comment]
currently attempting to get minecraft to run and receiving this. This isn't really all that important, but I would like to figure out whats happening.

**Comment by OtterCodes101** [comment]
If you wanna play minecraft, use Prism Launcher, a free and open-source alternative to the minecraft launcher based off of multimc. The official minecraft launcher's linux team probably assumed all debian-like distros are ubuntu.

**Comment by solanuscasey** [comment]
interesting, I never had this problem running mc on a chrome device, is the distro shimboot uses modified in some capacity?

**Comment by OtterCodes101** [comment]
how exactly did you run it on chromeos

**Comment by solanuscasey** [comment]
the native linux installation. Chrome devices have the capability to run debian linux from a normal account.

**Comment by ading2210** [comment]
The official Minecraft launcher is very slow (I've seen it use over 1GB of memory before), so you should be using PrismLauncher for performance reasons anyways.

**Comment by solanuscasey** [comment]
I will be likely running BLC or prism once I get a decent flash drive(over 400 mb/s). I'm mainly just wondering about this distro and compatibility with other programs such as wine. Is there detailed documentation somewhere?

**Comment by OtterCodes101** [comment]
its literally just vanilla debian with the systemd patched to work under the RMA shim kernel
