### ISSUE TITLE
Chromebook crashes when using an SD card but works fine when using a flash drive

### ISSUE THREAD

**Issue by WeirdPerson420** [ading2210/shimboot#12]
If I write shimboot to a flash drive it works perfectly however with an SD card the Chromebook immediately shuts off after choosing default. If it helps my flash drive is a 16gb from MicroCenter and my SD card is a 32gb SanDisk.

**Comment by OtterCodes101** [comment]
Your SD card could be bad.

**Comment by WeirdPerson420** [comment]
I tried another SD card (SanDisk 16gb) and that didn't work either also it seems to crash right as it says "moving mounts to newroot"

**Comment by zek-c** [comment]
wait do SD cards have a different way of mounting? instead of /dev/sdc1 or whatever its possibly /dev/sd1 or something else? that could be a possible bug. not sure, havent examined the code of shimboot. it could also be they way the SD is formatted/partitioned. or just a general board bug.

**Comment by ading2210** [comment]
SD cards use `/dev/mmcblkX` usually, but this shouldn't affect how shimboot functions.

**Comment by zek-c** [comment]
well dont eMMC use the same thing? it could be an issue with not using the right disk and attempting to mount to an important partition so it stops it from happening. just a guess though, im not really familiar with eMMC and this specific topic so i shoudlnt have a place here
