### ISSUE TITLE
How to edit vpd data?

### ISSUE THREAD

**Issue by LavedenC1** [ading2210/shimboot#120]
Hello, I was wondering if its possible to edit the vpd data, by going into the shell from the options menu. The data is at /sys/firmware/vpd and i cant modify it even with chmod.

**Comment by ading2210** [comment]
I believe if you boot into Chrome OS you should be able to edit it. You shouldn't be able to from the bootloader since you need a particular program to modify it that is only available on Chrome OS.

**Comment by LavedenC1** [comment]
@ading2210 The problem is the Chrome OS booting isn't working.
Issue #20

**Comment by ading2210** [comment]
Try booting Chrome OS in rescue mode.
