### ISSUE TITLE
Desktop Environment 

### ISSUE THREAD

**Issue by NikhilKonduru8** [ading2210/shimboot#124]
What is the full process of using a new environment? Like after downloading how do I use the new environment?

**Comment by Fighterhen63** [comment]
@NikhilKonduru8 So you need a terminal if you do not have another computer I recommend using a prebuilt version of shimboot, and then fallow these steps. First open terminal and run: **sudo apt install git** then run **git clone https://github.com/ading2210/shimboot.git** then run **cd shimboot** (If it shows that it does not exist run cd then run cd shimboot). After this run the fallowing command sudo ./build_complete.sh [YOUR MOTHERBOARD CODENAME for ex: dedede] desktop=[Whatever desktop environment you want place here. The valid values for this argument are: gnome, xfce, kde, lxde, gnome-flashback, cinnamon, mate, and lxqt.]. Once this process completes, check the folder it says the final image was made, then transfer the file over to the computer you are using to make your chrome recovery image, if your using the same SD Card make sure to copy the final image (shimboot.bin) to your computer. If you don't have another computer get out of debian and re run the shimboot then go into chrome. From here you can copy the file off your SD Card onto your Chromebook internal storage then you can flash the SD Card from there. Requiring just one computer in total. Hope those helps!

**Comment by ading2210** [comment]
You may also run `sudo tasksel` to switch the desktop environment on an existing shimboot install.

**Comment by NikhilKonduru8** [comment]
> You may also run `sudo tasksel` to switch the desktop environment on an existing shimboot install.

what do I do after selecting the environment
