### ISSUE TITLE
Steam compat issue [Debian]

### ISSUE THREAD

**Issue by Sillylittleguy1** [ading2210/shimboot#127]
**To Reproduce**
sudo apt install steam

**Expected behavior**
steam should install

**Additional context**
i am aware that Debian is the one responsible for hosting the files, however the README claims the command above works. additionally, i have attempted to install it in other roundabout ways. eg: the raspberry pi app manager, installing all required dependencies.

it would be nice to have a link or tutorial to refer to that has been tested on shimboot

**Comment by NikhilKonduru8** [comment]
"sudo -i" and then the sudo apt install steam

**Comment by ading2210** [comment]
What board are you on? 

Please don't delete the issue template that asks for system information when reporting a bug.

**Comment by Sillylittleguy1** [comment]
ah, my bad. i am on corsola gen4 Chromebook with enrolment

**Comment by ading2210** [comment]
Corsola is an ARM board. Steam only support x86_64 so it will not work anyways. You might have more luck installing the box64 emulator but I don't have experience with this so I can't help with that.
