### ISSUE TITLE
SD card cannot expand storage

### ISSUE THREAD

**Issue by isuckatnames865** [ading2210/shimboot#129]
When I try to expand the storage, I get this error message:
Automatically detected root filesystem:
Disk /dev/mmcblk0: 117.75 GiB, 126437294080 bytes, 246947840 sectors
Units: sectors of 1 * 512 = 512 bytes

Automatically detected root partition:
/dev/mmcblk0p4 110592 9078750 8968159  4.3G Linux filesystem

Press enter to continue, or ctr+c to cancel. 

Before:
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p4  4.2G  3.7G  250M  94% /

Expanding the partition and filesystem...
FAILED: failed to get start and end for /dev/mmcblk052 in /dev/mmcblk0

I am using the prebulilt image for dedede, and running the prebuilt on an sd card, and tried using this [script](https://github.com/ading2210/shimboot/issues/60#issuecomment-2327864340) on root to no avail

**Comment by ading2210** [comment]
What did you do to run the new script when you tried it?

**Comment by isuckatnames865** [comment]
typed in "su" and then pasted in the code in the terminal

**Comment by Fighterhen63** [comment]
Run sudo growpart /dev/mmcblk0 4
then sudo resize2fs /dev/mmcblk0p4

(If these don't work then switch them around sudo growpart /dev/mmcblk0p4 then sudo resize2fs /dev/mmcblk0 4)

**Comment by Fighterhen63** [comment]
If when you run the first command and terminal just does not finish just open a new terminal window and run the second command. It should finish the first command and execute the second one.

**Comment by isuckatnames865** [comment]
Fixed the issue, thanks
