### ISSUE TITLE
PEAP Wifi not working on nissa

### ISSUE THREAD

**Issue by nathblade16** [ading2210/shimboot#134]
**Describe the bug**
My friend using shimboot debian is not able to connect to a wpa 2 enterprise wifi network using PEAP

**To Reproduce**
1. Connect to PEAP wifi
2. wait
3. get password prompt

**Expected behavior**
It connnects

**Screenshots / Photos**
If applicable, add screenshots or photos to help explain your problem.
![thingo](https://github.com/user-attachments/assets/f3e9211e-22ba-4367-b834-327ec0acbc75)

If you are reporting an issue with the build process, please run the scripts in debug mode by putting `DEBUG=1` before the build commmand, like `sudo DEBUG=1 ./build_complete.sh`.

**Target Chrome OS Device (please complete the following information):**
 - Board Name (e.g. nissa)
 - Device Name (e.g. pujjo) 
 - Shimboot version (e.g. v1.0.1) 

**Build Device (please complete the following information):**
 - OS: Debian 12
 - Neofetch out [run `neofetch --stdout` and paste it here]
 user@shimboot-nissa  
-------------------  
OS: Debian GNU/Linux 12 (bookworm) on Chrome OS x86_64  
Host: Pujjo rev3  
Kernel: 5.15.74-14076-g631ce1c040cc  
Uptime: 13 mins  
Packages: 2722 (dpkg)  
Shell: bash 5.2.15  
Resolution: 1920x1200  
DE: Plasma 5.27.5  
WM: kwin  
Theme: [Plasma], Breeze [GTK2/3]  
Icons: [Plasma], Tela-circle-dark [GTK2/3]  
Terminal: konsole  
CPU: Intel N100 (4) @ 3.400GHz  
GPU: Intel Alder Lake-N [UHD Graphics]  
Memory: 2905MiB / 7802MiB 

**Additional context**
school wifi uses PEAP

**Comment by Fighterhen63** [comment]
@nathblade16 Make sure the it looks smth like this but w/ your username and password 
![image](https://github.com/user-attachments/assets/6366fb4c-53cd-4f35-a712-ec63f51d50d5)

**Comment by nathblade16** [comment]
> @nathblade16 Make sure the it looks smth like this but w/ your username and password ![image](https://private-user-images.githubusercontent.com/133062458/378854456-6366fb4c-53cd-4f35-a712-ec63f51d50d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MzUwODIsIm5iZiI6MTcyOTYzNDc4MiwicGF0aCI6Ii8xMzMwNjI0NTgvMzc4ODU0NDU2LTYzNjZmYjRjLTUzY2QtNGYzNS1hNzEyLWVjNjNmNTFkNTBkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQyMjA2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2I0ZTg1MzU4MjJjZDdlNGFiMDllYWVlYzk1YjZhZDczMjFiNTEwNDllNzAyMzUxNDBkMWQyNTI2N2IzZGEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ipOXA9Ukb-zUzzzn0EKH0GJq5hn2YnKc5eSbUamG2Is)

for context I connect with this screen and then it gets stuck then asks for a password

**Comment by ading2210** [comment]
Does it work if you boot into Chrome OS through shimboot?

**Comment by nathblade16** [comment]
> Does it work if you boot into Chrome OS through shimboot?

Yes

**Comment by nathblade16** [comment]
> Does it work if you boot into Chrome OS through shimboot?

I'll check tomorrow, this is my friends chromebook

**Comment by nathblade16** [comment]
> > Does it work if you boot into Chrome OS through shimboot?
> 
> I'll check tomorrow, this is my friends chromebook

sorry for taking 4 days (adhd) but it does work in chromeOS booted through shimboot (I booted shimboot, selected boot chromeOS then root-a)

**Comment by ading2210** [comment]
Can you send the output of `lsmod` (as a text file) when booted in Chrome OS as well as Debian? It's probably missing a kernel module when in Debian so I need to compare which ones are loaded in Chrome OS vs Debian.

**Comment by nathblade16** [comment]
I'll do it next week but lsmod when chromeos??? Does shimboot dev mode?

**Comment by ading2210** [comment]
You can switch to a root console using vt2 by hitting ctr+alt+f2.

**Comment by nathblade16** [comment]
> You can switch to a root console using vt2 by hitting ctr+alt+f2.

I'm aware, I've used chrultrabook on my personal Chromebook

**Comment by nathblade16** [comment]
fixed by changing the capitilisation of the wifi name (for some reason linux did not find the capitilisation by itself)
