### ISSUE TITLE
Simply chrome OS

### ISSUE THREAD

**Issue by Kittycat7J** [ading2210/shimboot#135]
I am looking for something similar to this however I am worried it will be obvious that I am using Linux and would rather use a regular chrome OS system simply on a USB so it is not writing to the computer. the same as this works but without installing Linux. I am not asking for support from here doing that unless you want to simply if you know of a repository that would help with my specific needs.

**Comment by Kittycat7J** [comment]
My Chromebook is enrolled and I am wondering if this can be used to use an unenrolled version of chrome os

**Comment by adhdkiddy** [comment]
If you wanna use chromeos then use this unless you are on octopus then use terraos and this prebuilt v109 image at https://files.mercurywork.shop/r58playz/terraos/chromeos-109-images/

May not be unenrolled but it has compabillity for skiovox

**Comment by adhdkiddy** [comment]
> My Chromebook is enrolled and I am wondering if this can be used to use an unenrolled version of chrome os. Thanks for the suggestion

This will work if you arent on octopus

**Comment by ading2210** [comment]
Shimboot already works for running an unenrolled version of Chrome OS, however it does not run from a USB drive by default.

**Comment by adhdkiddy** [comment]
Yes but octopus kernel Isnt supported loading newer versions so loading an older version via terraos fixes that @ading2210
