### ISSUE TITLE
Device compatibility report for: (gen4 corsola)

### ISSUE THREAD

**Issue by Sillylittleguy1** [ading2210/shimboot#136]
This template is not meant to be used if Shimboot fails completely. Submit a bug report instead.

**Compatibility Info**:
- Board Name: (corsola)
- X11: yes
- Wifi: yes
- Internal Audio: untested (what should i install to add speaker compat?)
- Backlight: yes
- Touchscreen: untested(i do not have touchscreen)
- 3D acceleration: yes (llvmpipe (LLVM 15.0.6, 128 bits))
- Bluetooth: yes [PIPEWIRE REQUIRED FOR AUDIO]
- Webcam: untested

**Other Notes:**: seems like most of these can be fixed by adding the required packages to the default install

**Comment by adhdkiddy** [comment]
Llvmpipe is not 3d accel, its cpu rendering

**Comment by adhdkiddy** [comment]
Try following the instructions in the readme and create a file at /etc/X11/xorg.conf.d/20-intel.conf using nano or whatever and set it to this

Section "Device"
Identifier "Intel Graphics"
Driver "Intel"
Option "AccelMethod" "sna"
EndSection

**Comment by Sillylittleguy1** [comment]
> Try following the instructions in the readme and create a file at /etc/X11/xorg.conf.d/20-intel.conf using nano or whatever and set it to this
> 
> Section "Device" Identifier "Intel Graphics" Driver "Intel" Option "AccelMethod" "sna" EndSection

i dont know if it is intel since im on a ARM system

**Comment by adhdkiddy** [comment]
then i have no idea, probably some other config but that is the only one i know of

**Comment by ading2210** [comment]
I've updated the device compatibility table with this info, thanks.
