### ISSUE TITLE
Device compatibility report for: Jacuzzi (HP 11 G8 EE Chromebook)

### ISSUE THREAD

**Issue by Apersonwithnam** [ading2210/shimboot#138]
**Compatibility Info:**
- Board Name: Jacuzzi
- X11: Yes
- Wifi: Yes
- Internal Audio: No
- Backlight: Yes
- Touchscreen: untested
- 3D acceleration: untested ( I'm not sure )
- Bluetooth: No
- Webcam: Yes

**Other Notes:**
The 'Suspend' feature _kinda_ works on the gnome desktop ( I built it with `sudo ./build_complete.sh jacuzzi desktop=gnome` using the pre-built board) it isn't like the pre-built board that just shuts the computer off, if you close the lid you have the same amount of time as the inactivity timer. The night light doesn't work for me though ( The thingy that turns the screen orange).

**Comment by ading2210** [comment]
This is basically already known and already listed in the compatibility table.
