### ISSUE TITLE
Trying to open any .mp4 file crashes Debian 

### ISSUE THREAD

**Issue by Fighterhen63** [ading2210/shimboot#142]
My SD Card is a sandisk 128 gb SD Card known working. 

Whenever I try to open an .mp4 file it will just freeze my screen, it will play the video, but it cannot be seen because the screen is frozen. 

**To Reproduce**
1. Boot into shimboot Debian 
2. Open file manger
3. Then double click on the .mp4 file
4. The screen will freeze and it will  not return to normal. 

I should be able to open an .mp4 file and it just open up the video player without crashing the OS. 

![image](https://github.com/user-attachments/assets/fefc7016-de85-483e-ba6b-326e60ac299f)

 - Board Name: Dedede
 - Device Name: Acer c734 
 - Shimboot version: 1.2.1
 - OS: Debain 12 Gnome

**Comment by ading2210** [comment]
Did you try a different video player like VLC?

**Comment by Fighterhen63** [comment]
Installing VLC and setting it to the default application for videos did fix the issue, ig there just something wrong with the default videos application.
