### ISSUE TITLE
I kinda need help

### ISSUE THREAD

**Issue by FlappyChiken** [ading2210/shimboot#144]
Im new to this Linux Distro and i have no idea how to open files. (Help Plz)

**Comment by Fighterhen63** [comment]
On XFCE? I'm assuming you used a prebuilt. There should be an applications button click on that and navigate to the file manager. Once in there you can open your files.  If you want to learn abt it check this video out: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjVydCC1bSJAxXQHTQIHbe8JtoQwqsBegQIEBAF&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D6fN2tPiNF3U&usg=AOvVaw3PYlFHYsQNFvJukszXZqWO&opi=89978449

**Comment by ading2210** [comment]
https://www.google.com/search?q=how+to+use+xfce

**Comment by FlappyChiken** [comment]
are you sure? do .deb files not work?

**Comment by FlappyChiken** [comment]
I thought they would becuase .deb is made for debian

**Comment by Fighterhen63** [comment]
@FlappyChiken Run in terminal: cd Downloads (or where ever your file is) then run sudo apt install ./(Package Name Goes Here) then put in your password, and there ya go
