### ISSUE TITLE
file cant resize

### ISSUE THREAD

**Issue by Clone-trooper-9904** [ading2210/shimboot#145]
I don't know how to fix this but i cant resize anything,
please help me i'm an idiot 

![Screenshot_2024-10-30_00-19-39](https://github.com/user-attachments/assets/43a72081-1ddb-4b2e-9333-14b5a0f1ddda)

**Comment by FlappyChiken** [comment]
Bro i have no idea, could u help me with my problem please?

**Comment by FlappyChiken** [comment]
Im new to Debian (And Linux in General) How do I open Files?

**Comment by Clone-trooper-9904** [comment]
did you have this problem?

**Comment by Clone-trooper-9904** [comment]
> Bro i have no idea, could u help me with my problem please?

Im new to linux to

**Comment by Clone-trooper-9904** [comment]
> > Bro i have no idea, could u help me with my problem please?
> 
> Im new to linux to

so im a dumb brain to it

**Comment by FlappyChiken** [comment]
same here ngl

**Comment by FlappyChiken** [comment]
but i need help to

**Comment by FlappyChiken** [comment]
HOW DO I OPEN FILES

**Comment by Clone-trooper-9904** [comment]
where's the file located

**Comment by Clone-trooper-9904** [comment]
> HOW DO I OPEN FILES

Where's the file located?

**Comment by FlappyChiken** [comment]
in downloads i think

**Comment by FlappyChiken** [comment]
🤯

**Comment by Clone-trooper-9904** [comment]
kind of file?

**Comment by Clone-trooper-9904** [comment]
idk than

**Comment by Clone-trooper-9904** [comment]
sorry

**Comment by ading2210** [comment]
@Clone-trooper-9904 The disk you need to resize is `mmcblk0` not `mmcblk1`
