### ISSUE TITLE
Question to ading2210 (Im so confused)

### ISSUE THREAD

**Issue by FlappyChiken** [ading2210/shimboot#146]
I understand that you will most likely label this as "Invalid", but when ever I perform the 'sudo dpkg -i <package path>' command it says "could not access archive". The file was .deb (The Minecraft Launcher), and I have litterally no idea what to do. Some feedback would be great! 
-Thanks, FlappyChiken

**Comment by FlappyChiken** [comment]
DOES ANYONE HAVE ANY IDEAS

**Comment by ading2210** [comment]
https://unix.stackexchange.com/questions/159094/how-to-install-a-deb-file-by-dpkg-i-or-by-apt

This is a question that pertains to Debian in general, not Shimboot. This is not the right place to ask.

**Comment by Fighterhen63** [comment]
@FlappyChiken Try a few things, 
(You don't have to do any of these in any order just some different things to try).
sudo dpkg -i /path/to/file/MinecraftLauncher.deb


ls /path/to/file/


chmod +r /path/to/file/MinecraftLauncher.deb
