### ISSUE TITLE
Broken desktop??

### ISSUE THREAD

**Issue by Sillylittleguy1** [ading2210/shimboot#147]
**Describe the bug**
Boots like usual, until you login and it's just the desktop bg and mouse. [no key combos work(ctrl+alt+f2,refresh,light up)]

**To Reproduce**
Play gmod<
Lag the desktop<
power down<
Boot into Debian<
Login<
Sad.jpg

**Expected behavior**
A desktop should load!!

**Screenshots / Photos**

**Target Chrome OS Device (please complete the following information):**
 - Board Name (corsola)
 - Device Name (no idea bc I'm basically bricked) 
 - Shimboot version (latest) 

**Additional context**
I can provide any and all files at request. Hell, you can take my entire os.

**Comment by Sillylittleguy1** [comment]
News: I cannot physically see the terminal, but I can use it. Running startx brings me to a black screen

**Comment by ading2210** [comment]
Did you expand the rootfs like the documentation says?

**Comment by ading2210** [comment]
Can you check that the disk didn't get filled in the meantime? Also, try checking for disk corruption using fsck from a different devices.

**Comment by Sillylittleguy1** [comment]
It's a 180 GB USB form Samsung. (I am 100% sure it's not a fake) And the xorg logs show some errors if you want to look at em'

**Comment by ading2210** [comment]
I don't think Samsung makes 180GB USB drives. They're either 128GB or 256GB.

**Comment by Sillylittleguy1** [comment]
∆ yeah that one

**Comment by Sillylittleguy1** [comment]
Uhhhh even after fully reinstalling, its still broken, and this time it just completely shuts down
