### ISSUE TITLE
Infinite Login To Gnome 

### ISSUE THREAD

**Issue by Fighterhen63** [ading2210/shimboot#148]
My SD Card is a sandisk 128 gb SD Card known working.

After just a normal reboot trying to login the the desktop Gnome it just returns to the login screen. I thought my SD might of had some issue, but all files are still on it. Then I tried loading anyother desktop such as Gnome Xorg and it booted just fine. 

To Reproduce

Boot into shimboot Debian
Try To Login 
Then If you have the issue it will just return to the same screen. 
(This one will be hard to reproduce i'd assume.)
![image](https://github.com/user-attachments/assets/6714f376-9b37-492f-84ed-0f0ab7b9a134)

Board Name: Dedede
Device Name: Acer c734
Shimboot version: 1.2.1
OS: Debain 12 Gnome (Right now i'm using Gnome Xorg)

**Comment by Inglan** [comment]
might be an issue with gpu accel, this happens with hyprland

**Comment by Fighterhen63** [comment]
Okay, How would I fix this then?

**Comment by Inglan** [comment]
> Okay, How would I fix this then?
> 

Just asking, is there a transition when you select your username? If so that means gpu accel is working and I don't know what the problem could be. If no transition there is smth in the docs about gpu acceleration.

**Comment by Fighterhen63** [comment]
Well when I click on my user name it does the kind of fade thing and then there's my username. When I enter my user name that page disappears and then acts like its going to boot but then returns to he login screen.

**Comment by Inglan** [comment]
Hmm. See if you can check logs

**Comment by ading2210** [comment]
You should probably just use Xorg then. Wayland is unreliable in general.

**Comment by inquestor420** [comment]
DUDE I HAD THE SAME ISSUE SO WHILE YOUR AT THE PASSWORD SCREEN LOOK DOWN TO THE BOTTOM RIGHT AND YOU WILL SEE A SETTING ICON CLICK THAT CHOOSE XFCE THEN PUT IN UR PASSWORD (go to terminal after) THEN UNINSTALL GNOME (you can keep your extensions there's a option to keep them) THEN REINSTALL GNOME AND IT WILL WORK AGAIN
