### ISSUE TITLE
How to get KDE

### ISSUE THREAD

**Issue by FlappyChiken** [ading2210/shimboot#149]
This will also prob get marked as invalid but i need to know how to load KDE

**Comment by FlappyChiken** [comment]
The command featured doesn't work

**Comment by Inglan** [comment]
build your own shimboot image with debian, or run
```
sudo apt update
sudo apt install kde-standard
```
in a terminal
when you are at login screen (i assume you are using the default one in the prebuilt image, you can select kde up the top

**Comment by FlappyChiken** [comment]
thx

**Comment by FlappyChiken** [comment]
HELP @Inglan should i use lightdm or sddm

**Comment by FlappyChiken** [comment]
I already clicked sddm, if it was the wrong one how do i change it?

**Comment by ading2210** [comment]
You can run `sudo tasksel` to switch the desktop environment on an existing Debian install. The choice of lightdm vs sddm doesn't matter since both will work.
