### ISSUE TITLE
Question because i don't have the ability to answer the question myself

### ISSUE THREAD

**Issue by funkymokey** [ading2210/shimboot#150]
Because of many chromebooks being broken in my 8th grade year back in 2021. My district has chromebooks in each classroom rather than letting a student own their own chromebook.
This question being, if i boot up a USB with the hana bin file. Can i simply continue booting using the other chromebooks? It's all the same board. And I cannot find out myself as of now, since im trying to get myself a micro-sd to sd card converter since the chromebooks use the regular sd slot. 

And question because im a moron, where do you find the file after building it using the terminal? (I built it using arch linux)

**Comment by Fighterhen63** [comment]
@funkymokey I highly discourage you from doing this on devices that are going to not be yours... I mean if its like it is yours just in the classroom than whatever I guess. Just know that this will wipe ChromeOS so you will have to have a USB to bring it back to the normal enrolled chromeOS. You should be able to find the file in shimboot/ folder, look for the bin file shimboot(motherboard name).bin it should be around 5 ish GB. But like I stated before if you are going around to different computers, and if they don't have force enrollment this could cause a lot of problems, and most likely would result in you getting in trouble.

**Comment by funkymokey** [comment]
> @funkymokey I highly discourage you from doing this on devices that are going to not be yours... I mean if its like it is yours just in the classroom than whatever I guess. Just know that this will wipe ChromeOS so you will have to have a USB to bring it back to the normal enrolled chromeOS. You should be able to find the file in shimboot/ folder, look for the bin file shimboot(motherboard name).bin it should be around 5 ish GB. But like I stated before if you are going around to different computers, and if they don't have force enrollment this could cause a lot of problems, and most likely would result in you getting in trouble.

The Chromebooks are force enrolled, and my schools network has around 200GB of space per student. Since the Chromebooks themselves only have 32GB, and only around 500MB is usable, and to mention we do not download anything. (I've done some testing and simply restarting and removing the USB easily lets the Chromebook return to its original state)

**Comment by ading2210** [comment]
Please don't use shimboot on shared devices.
