### ISSUE TITLE
apt autoremove removes windowmanager!

### ISSUE THREAD

**Issue by Sillylittleguy1** [ading2210/shimboot#151]
**Describe the bug**
used apt autoreove
**To Reproduce**
1.install a bunch of stuff
2."packages were automatically installed and no longer needed:"
3. apt autoremove. 
4. reboot

**Expected behavior**
remove packages un-needed by sys

*
**Target Chrome OS Device (please complete the following information):**
 - Board Name (rusty)
 - Device Name (corsola) 
 - Shimboot version (latest) 

**Additional context**
this is what happened on my previous bug about my black screen, it was this!

**Comment by ading2210** [comment]
Can you be more specific about how to reproduce this issue?

**Comment by Sillylittleguy1** [comment]
The "INSTALL A BUCH OF STUFF" step basically just means: install enough packages and eventually autoremove will list necessary packages for removal.

**Comment by Fighterhen63** [comment]
@Sillylittleguy1 Oh and I bet this is why my thing won't boot into the desktop...

**Comment by Sillylittleguy1** [comment]
∆unfortunately

**Comment by Sillylittleguy1** [comment]
FIXED THE ISSUE

**Comment by Fighterhen63** [comment]
> FIXED THE ISSUE: manually added a cron script that activates every reboot and re-installs all default packages

Could you like send that file to my email fighterhen63@gmail.com please 🙏🙏
