### ISSUE TITLE
It’s stuck loading when I put my user and pass in 

### ISSUE THREAD

**Issue by inquestor420** [ading2210/shimboot#152]
https://github.com/user-attachments/assets/1e13caa5-70ff-4389-a0e3-68307200c52a

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Photos**
If applicable, add screenshots or photos to help explain your problem.

If you are reporting an issue with the build process, please run the scripts in debug mode by putting `DEBUG=1` before the build commmand, like `sudo DEBUG=1 ./build_complete.sh`.

**Target Chrome OS Device (please complete the following information):**
 - octopus 
 - STEEL-IX-VZSZ
  this page has a list of them: https://chromiumdash.appspot.com/serving-builds -->
 - Shimboot version (e.g. v1.0.1) 

**Build Device (please complete the following information):**
 - OS: [e.g. Debian 12]
 - Neofetch out [run `neofetch --stdout` and paste it here]

**Additional context**
 So I left it like that for a few hours and it still didn’t load I think it’s because I installed bottles.deb or steam.deb but now it just won’t load. And I have a lot of stuff on it that I can’t loose or it would take me another 10 hours to get the stuff I had back

**Comment by ading2210** [comment]
Did you expand the rootfs?

**Comment by inquestor420** [comment]
> Did you expand the rootfs?

No

**Comment by ading2210** [comment]
This is one of the things that can happen if you don't follow the instructions and don't expand the rootfs as directed. 

To fix this, go into rescue mode (type `rescue 3`) then run `expand_rootfs`.

**Comment by inquestor420** [comment]
> This is one of the things that can happen if you don't follow the instructions and don't expand the rootfs as directed. 
> 
> 
> 
> To fix this, go into rescue mode (type `rescue 3`) then run `expand_rootfs`. 

It says this ![image](https://github.com/user-attachments/assets/d0947aba-879e-4fc3-97c4-56e4aff291a7)

**Comment by inquestor420** [comment]
> This is one of the things that can happen if you don't follow the instructions and don't expand the rootfs as directed. 
> 
> 
> 
> To fix this, go into rescue mode (type `rescue 3`) then run `expand_rootfs`. 

Yea that didn't fix it it's still stuck loading and i think i already expanded rootfs a while ago so is there anything else i can do
