### ISSUE TITLE
Owner closed my original issue but the thing he said to do didn't work because I already did that when I first booted it

### ISSUE THREAD

**Issue by inquestor420** [ading2210/shimboot#154]
To Reproduce

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior

Screenshots / Photos
If applicable, add screenshots or photos to help explain your problem.

If you are reporting an issue with the build process, please run the scripts in debug mode by putting DEBUG=1 before the build commmand, like sudo DEBUG=1 ./build_complete.sh.

Target Chrome OS Device (please complete the following information):

octopus
STEEL-IX-VZSZ
this page has a list of them: https://chromiumdash.appspot.com/serving-builds -->
Shimboot version (e.g. v1.0.1)
Build Device (please complete the following information):

OS: [e.g. Debian 12]
Neofetch out [run neofetch --stdout and paste it here]
Additional context
So I left it like that for a few hours and it still didn’t load I think it’s because I installed bottles.deb or steam.deb but now it just won’t load. And I have a lot of stuff on it that I can’t loose or it would take me another 10 hours to get the stuff I had back and also I talked to the owner he said to expand-rootfs then closed my issue but it still didn't work so please help me fully fix it

**Comment by adhdkiddy** [comment]
yeah for some reason shimboot bricks when you change your password

**Comment by inquestor420** [comment]
> yeah for some reason shimboot bricks when you change your password

I didn't change my password

**Comment by adhdkiddy** [comment]
> > yeah for some reason shimboot bricks when you change your password
> 
> I didn't change my password 

You didnt?

**Comment by adhdkiddy** [comment]
Thought you did as this same thing has happened to me once i changed login details

**Comment by adhdkiddy** [comment]
Might be bottles but i have no idea, ig your only option is to somehow repair it using another computer or reflash
