### ISSUE TITLE
Shimboot bricks when you change login details 

### ISSUE THREAD

**Issue by adhdkiddy** [ading2210/shimboot#155]
**Describe the bug**
Shimboot bricks when you change login details

**To Reproduce**
1. Change password using passwd
2. Reboot
3. Be unable to login with any details

**Expected behavior**
You should be able to log in with your new password

**Screenshots / Photos**
I dont wanna brick shimboot again so no

**Target Chrome OS Device (please complete the following information):**
 - Board Name: octopus
 - Device Name: phaser
 - Shimboot version: 1.2.1

**Additional context**
Bricks only when you change login details

**Comment by ading2210** [comment]
Can you send a video of this happening? I'm inclined to think this is user error considering `passwd` works fine for me and many other people.

**Comment by adhdkiddy** [comment]
I will send proof once i get to a place where i can reflash my micro sd
