### ISSUE TITLE
Is it possible to run windows  10 on shimboot

### ISSUE THREAD

**Issue by inquestor420** [ading2210/shimboot#156]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ading2210** [comment]
It is not possible, only Linux works.

**Comment by ColdBrewOfficial** [comment]
> [@ading2210](https://github.com/ading2210) Why not? Is it **TECHNICALLY** possible, but would take too much work, or just impossible?

Okay I know I am WAYYYYYYYYYYY to late with this reply, but due to the nature of the bootloader, its impossible. You have to program in pure machine code to make a custom windows bootloader, but that's too much work isn't it

**Comment by Zzza38** [comment]
at this point lets just skip past windows and go straight for linux @ColdBrewOfficial
