### ISSUE TITLE
Operation Not permitted

### ISSUE THREAD

**Issue by DogeLeader** [ading2210/shimboot#16]
this error happens when I use the command: sudo ./build_rootfs.sh data/rootfs bookworm:  

mknod: /workspace/shimboot/rootfs/test-dev-null: Operation not permitted
E: Cannot install into target '/workspace/shimboot/rootfs' mounted with noexec or nodev

![Error Screen](https://github.com/ading2210/shimboot/assets/146743206/add2f9e8-b82c-4eff-8589-691d1c3c2332)

**Comment by DogeLeader** [comment]
Alright, thanks.

**Comment by ading2210** [comment]
You can try remounting the filesystem with the `exec` and `dev` flags.

Find the mount point by doing `findmnt -T .`. On my PC this prints out the following:
```
TARGET SOURCE    FSTYPE OPTIONS
/      /dev/sdb2 ext4   rw,noatime
```
Now run `sudo mount -o remount,exec,dev {TARGET}`, replacing `{TARGET}` with the path listed as the target in the output of the previous command.

**Comment by DogeLeader** [comment]
what does the mountpoint look like

**Comment by DogeLeader** [comment]
where i the output is it?

**Comment by DogeLeader** [comment]
It says "permission denied"

**Comment by ading2210** [comment]
Can you send the output of the commands you're running?

**Comment by ading2210** [comment]
@DogeLeader Try running these commands in your terminal, I tested it to work on Github Codespaces:
```

mountpoint="$(findmnt -T . | tail -n1 | cut -f1 -d' ')"
mount -o remount,dev,exec "/workspaces"
```

**Comment by ading2210** [comment]
This was also fixed in the latest commit, so do a `git pull` and try again.

**Comment by DogeLeader** [comment]
abc@418b89848064:~/shimboot$ findmnt -T .
TARGET SOURCE                                                     FSTYPE OPTIONS
/config
       /dev/loop3[/codespacemount/workspace/DesktopOnCodespaces/Save]
                                                                  ext4   rw,node

**Comment by ading2210** [comment]
That looks to be right, you can try re-running the scripts now.

**Comment by DogeLeader** [comment]
what should i copy?

**Comment by DogeLeader** [comment]
Out of the output

**Comment by ading2210** [comment]
You don't need to copy anything, I've already fixed the bug here. Just clone the repository again and retry the build.

**Comment by DogeLeader** [comment]
oh alright ill try

**Comment by DogeLeader** [comment]
sudo ./build_rootfs.sh data/rootfs bookworm

**Comment by DogeLeader** [comment]
mount: /config: permission denied.

**Comment by ading2210** [comment]
Did you delete and clone the repository again from scratch?

**Comment by DogeLeader** [comment]
yep

**Comment by ading2210** [comment]
Try running `sudo DEBUG=1 ./build_rootfs.sh data/rootfs bookworm`, and copy-paste the *entire output* of that command.

**Comment by DogeLeader** [comment]
+ . ./common.sh
++ set -e
++ '[' 1 ']'
++ set -x
++ export DEBUG=1
++ DEBUG=1
+ assert_root
+ '[' 0 -ne 0 ']'
+ assert_deps 'realpath debootstrap'
+ local 'needed_commands=realpath debootstrap'
++ check_deps 'realpath debootstrap'
++ local 'needed_commands=realpath debootstrap'
++ for command in $needed_commands
++ command -v realpath
++ for command in $needed_commands
++ command -v debootstrap
+ local missing_commands=
+ '[' '' ']'
+ assert_args bookworm
+ '[' -z bookworm ']'
+ parse_args data/rootfs bookworm
+ declare -g -A args
+ for argument in "$@"
+ '[' data/rootfs = -h ']'
+ '[' data/rootfs = --help ']'
++ echo data/rootfs
++ cut -f1 -d=
+ local key=data/rootfs
+ local key_length=11
+ local value=
+ args["$key"]=
+ for argument in "$@"
+ '[' bookworm = -h ']'
+ '[' bookworm = --help ']'
++ echo bookworm
++ cut -f1 -d=
+ local key=bookworm
+ local key_length=8
+ local value=
+ args["$key"]=
++ realpath -m data/rootfs
+ rootfs_dir=/config/shimboot/data/rootfs
+ release_name=bookworm
+ packages=''\''task-xfce-desktop'\'''
+ chroot_mounts='proc sys dev run'
+ mkdir -p /config/shimboot/data/rootfs
++ need_remount /config/shimboot/data/rootfs
++ local target=/config/shimboot/data/rootfs
+++ findmnt -T /config/shimboot/data/rootfs
+++ rev
+++ cut -f1 '-d '
+++ rev
+++ tail -n1
++ local mnt_options=rw,nodev,relatime
++ echo rw,nodev,relatime
++ grep -e noexec -e nodev
+ '[' rw,nodev,relatime ']'
+ do_remount /config/shimboot/data/rootfs
+ local target=/config/shimboot/data/rootfs
++ findmnt -T /config/shimboot/data/rootfs
++ tail -n1
++ cut -f1 '-d '
+ local mountpoint=/config
+ mount -o remount,dev,exec /config

**Comment by DogeLeader** [comment]
what  I do from here on?

**Comment by DogeLeader** [comment]
I figured it out the command only works when it is this: sudo ./build_rootfs.sh /data/rootfs bookworm. You have to add a / before data.

**Comment by DogeLeader** [comment]
I could not complete the process successfully. So I have one request, please add the: Jacuzzi board to the pre-built image uploads

**Comment by DogeLeader** [comment]
Thanks for all the tech support!

**Comment by DogeLeader** [comment]
I look forward to your response

**Comment by ading2210** [comment]
Jacuzzi is an ARM-based board, those are not supported yet. See issue #8

**Comment by DogeLeader** [comment]
Are you going to add arm support in the future?

**Comment by DogeLeader** [comment]
Because it would be very helpful.

**Comment by DogeLeader** [comment]
Not going lie, my the school has our Chromebooks locked down tight: Our Chromebooks are arm based and they have digital write protection.
