### ISSUE TITLE
MULTIPLE QUESTIONS

### ISSUE THREAD

**Issue by FlappyChiken** [ading2210/shimboot#161]
Once again I understand this will be marked as invalid because of all the empty information not being fulfilled but, 
1. Add more Linux Distros in the boot screen (Arch Linux, Linux Mint, Kali, etc)
2. HELP HOW TO GET NEOFETCH TO WORK????? PLEASE IM BEGGING U

**Comment by ading2210** [comment]
Please don't spam issues on the repo for things that are either already in the README or very easy to look up on Google.
