### ISSUE TITLE
WE NEED UBUNTU OR ARCH

### ISSUE THREAD

**Issue by FlappyChiken** [ading2210/shimboot#164]
I'm frustrated that Shimboot is limited to just Debian, and should expand to other Operating Systems

Add Ubuntu or Arch Linux which are both great in my opinion.

Any other Operating system would be cool as long as there is a new operating system to explore.

**Comment by funkymokey** [comment]
If you read the todo, those two operating systems are going to be added soon

**Comment by ading2210** [comment]
This is already in the todo. Also see #130
