### ISSUE TITLE
This is more of a question

### ISSUE THREAD

**Issue by FlappyChiken** [ading2210/shimboot#166]
**Describe the bug**
When i try to install Steam its tell me "Steam now requires user namespaces to be enabled", and won't let me open it
**To Reproduce**
Try to download steam on shimboot

**Expected behavior**
FOR IT TO WORK

**Comment by FlappyChiken** [comment]
PLZ HELP

**Comment by qloakongithub** [comment]
This is answered in the README. https://github.com/ading2210/shimboot?tab=readme-ov-file#steam-doesnt-work

**Comment by ading2210** [comment]
Please try to like, read.
