### ISSUE TITLE
E: Unable to correct problems, you have held broken packages. 

### ISSUE THREAD

**Issue by Dominicis1** [ading2210/shimboot#167]
Every time i try to install wine recently i keep getting "E: Unable to correct problems, you have held broken packages." Ive reinstalled shimboot dedede many times ive checked the sd card and it works fine ive looked up some stuff but it gets me no where ive updated the
packages. I just dont know what to do anymore. I would like some help please and thank you

**Comment by FlappyChiken** [comment]
idk bruv

**Comment by FlappyChiken** [comment]
@ading2210 (He'll help)

**Comment by funkymokey** [comment]
> @ading2210 (He'll help)

Literally what was the point of this

**Comment by Dominicis1** [comment]
> > @ading2210 (He'll help)
> 
> Literally what was the point of this
tbh idk

**Comment by Clone-trooper-9904** [comment]
is it like this?
![image](https://github.com/user-attachments/assets/c7b64d4e-c311-4b1f-865e-51686a590317)

**Comment by Inglan** [comment]
you need to add `sudo` before the command to run as root

**Comment by Inglan** [comment]
also i highly recommend not using chrome on linux, the performance is terrible, especially on wayland (it looks like you are using x11 with the default xfce desktop though)

just. use. firefox

**Comment by Inglan** [comment]
just looked at it further and looks like chrome needs `fonts-liberation` and that is not installed nor installable with the default repos.

not a package manager expert but this is my best guess

**Comment by Inglan** [comment]
ok, just realized installing chrome isn't your problem (I only saw the screenshot). you should just run `sudo apt --fix-broken install`. this is why i hate apt and use arch btw

**Comment by Fighterhen63** [comment]
Yeah i'm having this issue too, it was acting like this a few months ago too, but then it mysteriously fixed itself. Maybe we just have to wait.

**Comment by Dominicis1** [comment]
> is it like this? ![image](https://private-user-images.githubusercontent.com/182587126/385570525-c7b64d4e-c311-4b1f-865e-51686a590317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NDIzMDcsIm5iZiI6MTczMTY0MjAwNywicGF0aCI6Ii8xODI1ODcxMjYvMzg1NTcwNTI1LWM3YjY0ZDRlLWMzMTEtNGIxZi04NjVlLTUxNjg2YTU5MDMxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwMzQwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGEyMmM0YTg3ZGEyMjdhYTkxYzViOTAyMGVkN2UwYmFlNjEwZjk1MTE4NTEzMzNiOWYyMGYxMWViYmI4NDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HFwORodJ04u63S4ZmK52awz5xMTXk02b72ztFVl4v0U)

yea

**Comment by Dominicis1** [comment]
> Yeah i'm having this issue too, it was acting like this a few months ago too, but then it mysteriously fixed itself. Maybe we just have to wait.

i hope it fixes its self

**Comment by Dominicis1** [comment]
> ok, just realized installing chrome isn't your problem (I only saw the screenshot).
> 
> you should just run `sudo apt --fix-broken install` (with the sudo)
> 
> this is why i hate apt and use arch btw
> 
> edit: just hid the irrelevant comments

didnt work sadly

**Comment by FunnyCorgi** [comment]
when installing chrome from the deb file, you need to run `sudo dpkg -i <package_location_here>`

**Comment by FunnyCorgi** [comment]
@Clone-trooper-9904

**Comment by FunnyCorgi** [comment]
for the wine issue here is the tutorial:https://wine.htmlvalidator.com/install-wine-on-debian-12.html

**Comment by Inglan** [comment]
> > ok, just realized installing chrome isn't your problem (I only saw the screenshot).
> > you should just run `sudo apt --fix-broken install` (with the sudo)
> > this is why i hate apt and use arch btw
> > edit: just hid the irrelevant comments
> 
> didnt work sadly

output?

**Comment by Dominicis1** [comment]
> > > ok, just realized installing chrome isn't your problem (I only saw the screenshot).
> > > you should just run `sudo apt --fix-broken install` (with the sudo)
> > > this is why i hate apt and use arch btw
> > > edit: just hid the irrelevant comments
> > 
> > 
> > didnt work sadly
> 
> output?

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by Dominicis1** [comment]
I cant install the wine repository

**Comment by ading2210** [comment]
This was fixed today. You can do a `sudo apt update` and `sudo apt upgrade` to fix it. It was caused by the Shimboot repository being out of date due to a package build failing.

**Comment by Dominicis1** [comment]
> sudo apt upgrade

Thank you so much

**Comment by Fighterhen63** [comment]
@ading2210 I think is is broken again. It wont let me install it: 

`user@shimboot-dedede:~$ sudo apt install --install-recommends winehq-stable
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 winehq-stable : Depends: wine-stable (= 10.0.0.0~bookworm-1)
E: Unable to correct problems, you have held broken packages.
user@shimboot-dedede:~$ `

**Comment by Fighterhen63** [comment]
Nvm I fixed it I think I had a bad deb http://deb.debian.org/debian bookworm main contrib non-free-firmware
line
