### ISSUE TITLE
Snap does not work 

### ISSUE THREAD

**Issue by Fighterhen63** [ading2210/shimboot#170]
When trying to use sudo snap install is will return with an error. 

**To Reproduce**
1. Go to terminal and run sudo apt install snapd
2. Then run sudo snap install something
3. Get an error 

**Expected behavior**
I should be able to install snap applications  

**Target Chrome OS Device (please complete the following information):**
 - DEDEDE
  - Shimboot version Latest

 - OS: Debian 12 Gnome

Error: 
user@shimboot-dedede:~$ fix_bwrap
Fixing permissions for /usr/bin/bwrap
Steam not installed, so exiting early.
Done.
user@shimboot-dedede:~$ sudo snap install h
error: system does not fully support snapd: cannot mount squashfs image using
       "squashfs": ----- mount: /tmp/syscheck-mountpoint-2338360073: wrong
       fs type, bad option, bad superblock on /dev/loop0, missing codepage or
       helper program, or other error.

       dmesg(1) may have more information after failed mount system call.

       -----
user@shimboot-dedede:~$

**Comment by Fighterhen63** [comment]
@Inglan Heres the error, (im installing just something random to get the error). 
`user@shimboot-dedede:~$ fix_bwrap
Fixing permissions for /usr/bin/bwrap
Steam not installed, so exiting early.
Done.
user@shimboot-dedede:~$ sudo snap install h
error: system does not fully support snapd: cannot mount squashfs image using
       "squashfs": ----- mount: /tmp/syscheck-mountpoint-2338360073: wrong
       fs type, bad option, bad superblock on /dev/loop0, missing codepage or
       helper program, or other error.

       dmesg(1) may have more information after failed mount system call.

       -----
user@shimboot-dedede:~$ 
`

**Comment by ading2210** [comment]
Snap is unsupported due to missing features in the shim kernel. This is not a fixable issue.

**Comment by goober3853** [comment]
> `fix_bwrap`

Wait... you got flatpak working??
