### ISSUE TITLE
What is SystemMD, and why will it hang when booting linux?

### ISSUE THREAD

**Issue by Zzza38** [ading2210/shimboot#172]
I want to try to port other Linux distros to chromebook, but I don't understand what SystemMD is and why would it hang. Does anyone have any info?

**Comment by ading2210** [comment]
https://en.wikipedia.org/wiki/Systemd

It hangs on startup because it tries to mount a tmpfs with flags that the shim kernel disallows. A patch is needed to change those flags so that the kernel allows them.
