### ISSUE TITLE
is shimboot patched for v130?

### ISSUE THREAD

**Issue by Charlieis1nsan3** [ading2210/shimboot#174]
Is this patched I have everything but I'm not sure my Chromebook is able to do it. and I dont want to risk and then get my Chromebook bricked (if that's even possible)

**Comment by Charlieis1nsan3** [comment]
yippee I know to use shimboot but I was wondering if it was patched
are u on v130?

**Comment by Inglan** [comment]
i have heard reports of nissa shims being patched, but not sure

it shouldn't brick your deivce, and if it does, chromebooks are easy to recover. if you do brick it you just need to get a recovery image with chrome recovery util or chrome100.dev on a home computer

**Comment by Inglan** [comment]
the worst that can happen is chromeos is missing or damaged but shimboot shouldnt do anything to chromeos unless you use a command that modifies the internal drive (usually `/dev/mmcblk` or something)

**Comment by Charlieis1nsan3** [comment]
okey

**Comment by TheTruePerson** [comment]
> i have heard reports of nissa shims being patched, but not sure
> 
> it shouldn't brick your deivce, and if it does, chromebooks are easy to recover. if you do brick it you just need to get a recovery image with chrome recovery util or chrome100.dev on a home computer

Crap, I'm on nissa... I'll fact check that tomorrow.

**Comment by TheTruePerson** [comment]
Just tried it today - seems to be working fine. (I'm on version 130 on an acer chromebook 511 with the nissa board)

**Comment by Charlieis1nsan3** [comment]
I'm on dedede

**Comment by Fighterhen63** [comment]
@Charlieis1nsan3 dedede should still work, i've tested it out today on 5 different chromebooks fully updated. So you should be safe if your on DEDEDE. _no I idea about nissa though_

**Comment by ading2210** [comment]
Whether shimboot works or not does not depend on the OS version at all. Booting modified shims (and thus shimboot as a whole) is patched on Chromebooks manufactured after 2023. Older devices will always continue to work.

**Comment by Charlieis1nsan3** [comment]
Im on a jasper lake Chromebook from 2022?

**Comment by nathblade16** [comment]
> Whether shimboot works or not does not depend on the OS version at all. Booting modified shims (and thus shimboot as a whole) is patched on Chromebooks manufactured after 2023. Older devices will always continue to work.

what exact point though
