### ISSUE TITLE
No valid image detected

### ISSUE THREAD

**Issue by 0gottogo0** [ading2210/shimboot#180]
**Describe the bug**
Doesn't boot into linux with any drive and gives a "No valid image detected" error with a description of "Make sure your external disk has a valid recovery image, and re-insert the disk when ready."

**To Reproduce**
1. Download shimboot_nissa.zip
2. Create recovery media using that image via Chrome Recovery Util
3. Get into dev mode and plug in drive
4. Wait like a sec or two

**Expected behavior**
Load into bootloader

**Screenshots / Photos**
 
![image](https://github.com/user-attachments/assets/ccade63d-708a-44d1-adaf-2bfd7a5ab22c)

**Target Chrome OS Device (please complete the following information):**
 - Nissa
 - Craaskvin
 - Newest as of now

**Additional context**
Tried multiple drives:
- 32gb sd card
- 8gb sd card
- 8gb usb drive
- 16gb usb drive

**Comment by Noob0dooN** [comment]
you may need to re-enable dev mode

**Comment by adhdkiddy** [comment]
May be keyrolled if so rip

**Comment by Fighterhen63** [comment]
Press Power + Refesh then press tab please send a screenshot of that

**Comment by ading2210** [comment]
Chromebooks manufactured after 2023 won't boot modified shims. This is not a fixable issue.
