### ISSUE TITLE
Audio not working on spoofed chrome

### ISSUE THREAD

**Issue by Noob0dooN** [ading2210/shimboot#181]
**Describe the bug**
The audio is constantly muted and will not unmute

**To Reproduce**
Idk how to reproduce the error its always in effect

**Expected behavior**
I expect the audio to unmute

**Screenshots / Photos**
[Screen recording 2024-11-24 6.31.21 PM.webm](https://github.com/user-attachments/assets/7a591f18-ea42-4bcf-a34b-4d0833684d07)

**Target Chrome OS Device (please complete the following information):**
 - Board Name: DEDEDE
 - Device Name: I dont remember
 - Shimboot version: i got a prebuilt one so idk
 
**Additional context**
The same issue applies with headphones connected via aux (bluetooth not tested)

**Comment by FunnyCorgi** [comment]
https://github.com/ading2210/shimboot/blob/main/README.md?plain=1#L91

In readme, under TODO, adding2210 has written that audio on dedede doesn't work. I am almost entirely certain this is why this isn't working.

**Comment by Noob0dooN** [comment]
ok thank you @FunnyCorgi
