### ISSUE TITLE
reenrollment after powerwashing chromebook

### ISSUE THREAD

**Issue by lapi32** [ading2210/shimboot#184]
I have finals coming up and I would likely need to go back to enrolled chromeos before then, as if my teachers cant see my screen during the tests It would bring up some suspicion. If I go through the powerwashing process will my chromebook automatically enroll back into my school, and if so will I likely need to readd certain extensions (like the website blocker etc). just wondering so I can decide whether or not ill need to borrow one of the school provided replacements

**Comment by Noob0dooN** [comment]
If you go through the powerwashing process it will re-enroll unless you un-enrolled via sh1mmer but even then you can re-enroll with a option in the bottom left appearing when setting up the chromebook
Or you could just press N for invalid HWID when booting

**Comment by ading2210** [comment]
Your chromebook never gets unenrolled to begin with if you use Shimboot.
