### ISSUE TITLE
Adding touchscreen only mode

### ISSUE THREAD

**Issue by Noob0dooN** [ading2210/shimboot#185]
**Is your feature request related to a problem? Please describe.**
I use a Touchscreen chromebook and sometimes i like putting the keyboard in the back and holding the chromebook vertically
but shimboot does not allow auto rotation nor disabling the keyboard when its beyond 180 degrees

**Describe the solution you'd like**
I whould like the keyboard to be disabled when turned beyond 180 degrees and auto rotation when keyboard is beyond 180 degrees

**Describe alternatives you've considered**
To manually rotate the screen and have to activley avoid touching the keyboard wich is annoying

**Comment by ading2210** [comment]
This is not in the scope of Shimboot. You can probably configure your Linux desktop to do this.

**Comment by Noob0dooN** [comment]
> This is not in the scope of Shimboot. You can probably configure your Linux desktop to do this. 

Sorry for the confusion but i was talking about ChromeOS not linux
