### ISSUE TITLE
how do move xfcs linux to kde version

### ISSUE THREAD

**Issue by luffy5170** [ading2210/shimboot#190]
so I try to put  KDE desktop on the xfce linux so i can use the kde becuse i like it more than the xfce i try put (sudo apt install kde-plasma-desktop) and it install but it won't show it afther i use sudo apt update and restart it  any help

**Comment by nathblade16** [comment]
what

**Comment by TheTruePerson** [comment]
I think I know what you are saying. After running sudo apt install plasma-desktop, log out, and on the top right, click on the thing with a wrench (it's to the left of the accessibility icon) and then click on plasma (x11)

**Comment by luffy5170** [comment]
It work

**Comment by ading2210** [comment]
This is user error. You can change what desktop environment is launched before you log in.
