### ISSUE TITLE
Device compatibility report for: Lenovo 14e/School issued windows device

### ISSUE THREAD

**Issue by hikidisn** [ading2210/shimboot#199]
If  anybody knows of an app like Rufus or chrome recovery utility that doesn't require admin privileges on a windows device, but if you find a version that runs in a web browser that would be awesome.

**Comment by hikidisn** [comment]
Ok, come on bro

**Comment by ading2210** [comment]
If you don't have a device to flash the image from it's not my problem.

**Comment by hikidisn** [comment]
dude, all I'm asking for is if someone knows of a website. Im not asking for you to do the work for me.

**Comment by ading2210** [comment]
Go ask that question in the discussions section then not the issues.
