### ISSUE TITLE
Chatgpt says this is how you push shimboot into internal drive so I don't have to have USB for shimboot to work is this right???

### ISSUE THREAD

**Issue by bahabryra** [ading2210/shimboot#203]
To install **Shimboot** onto your internal storage so you don't need a USB plugged in every time, follow these general steps. (The process might vary slightly depending on your device and OS, so let me know if you're using a specific Linux distribution or firmware.)

---

### **1. Prerequisites**
- **Back up your data:** Modifying the bootloader can risk system instability or data loss.
- A USB drive with Shimboot working correctly (used as a live boot medium).
- Internet access for downloading necessary tools.

---

### **2. Boot into Shimboot from the USB**
1. Plug in the USB containing Shimboot.
2. Reboot your system and enter the **BIOS/UEFI settings** (usually by pressing a key like `Esc`, `Del`, `F2`, or `F12` during startup).
3. Set the USB as the primary boot device.
4. Boot into Shimboot using the USB drive.

---

#### Option 1: **Manually Copy Shimboot**
1. Mount the internal storage partition where your operating system or bootloader resides.
   - Common locations: `/boot/efi` or `/boot`.
   - If you're using UEFI, it's typically `/boot/efi`.
   
2. Copy the Shimboot files from the USB to the appropriate location on the internal drive:
   ```bash
   sudo cp -r /path/to/usb/shim/* /boot/efi/
   ```

3. Ensure the EFI partition is properly configured to boot Shimboot.

---

#### Option 2: **Using a Bootloader Tool**
1. Install a bootloader management tool like `grub-install` or `efibootmgr` (if not already present):
   ```bash
   sudo apt install grub-efi efibootmgr
   ```

2. Register Shimboot with your EFI firmware so it’s bootable:
   ```bash
   sudo efibootmgr --create --label "Shimboot" --loader /EFI/shimx64.efi
   ```

3. Verify Shimboot is added to the boot menu:
   ```bash
   sudo efibootmgr
   ```

   You should see Shimboot listed as a boot option.

4. Reboot, remove the USB, and test if Shimboot launches from the internal drive.

---

### **4. Set Shimboot as Default Boot Option**
To make sure Shimboot always runs:
1. Enter your BIOS/UEFI settings.
2. Locate the **Boot Order** or **Boot Priority** section.
3. Move Shimboot to the top of the list.
4. Save and exit.

---

### **5. Test**
- Remove the USB and reboot.
- Your system should boot using Shimboot from the internal storage.
- If there are issues, you can reinsert the USB and use it to troubleshoot.

---

**Comment by bahabryra** [comment]
btw does is debian the only operating system avalible

**Comment by funkymokey** [comment]
You need a USB drive to boot into Debian in the first place in order to install it to the internal drive

**Comment by bahabryra** [comment]
ik im asking after that






On Monday, December 16, 2024 at 06:06:51 PM CST, Jordan ***@***.***> wrote: 







You need a USB drive to boot into Debian in the first place in order to install it to the internal drive

**Comment by funkymokey** [comment]
You should be able to find the internal drive using the lsblk command

**Comment by bahabryra** [comment]
so i can push it into my internal storage so i dont have to have the usb drive to run shimboot???

---

sent via email

**Comment by funkymokey** [comment]
> so i can push it into my internal storage so i dont have to have the usb drive to run shimboot???
> […](#)
> --- sent via email

Yes, if you mount it to your internal storage you wont need a USB to run shimboot

**Comment by bahabryra** [comment]
could you explain how

---
sent via email

**Comment by funkymokey** [comment]
> [<img alt="@bahabryra" width="40" height="40" src="https://avatars.githubusercontent.com/u/160906216?s=80&amp;u=e7b664a5d15bae50f9a715fe2e150fc46ec91390&amp;v=4">](/bahabryra)

Could you send a picture with the output after running lsblk

**Comment by bahabryra** [comment]
i got a new Chromebook so I have to redo the shimboot thing but I cant rn I was just wondering for when I do it (I switched from octopus to dedede :( )

**Comment by BomberFish** [comment]
> Chatgpt says this is how

![92DBA89A-A894-4587-8C45-A4BFE50FDE64_4_5005_c](https://github.com/user-attachments/assets/fdc5f6a1-b914-47fa-8b15-453ff094a807)

**Comment by LavedenC1** [comment]
omg bro this is so wrong

**Comment by LavedenC1** [comment]
its literally in the FAQ
