### ISSUE TITLE
final question: if I want to run shimboot internally but dont want to remove the managed chromeOS so I can use the managed chromeOS at school and shimboot at home would that work or will shimboot be permently on the chromebook

### ISSUE THREAD

**Issue by bahabryra** [ading2210/shimboot#204]
yea so like if at school I wanna just use chromeOS (managed) but at home I wanna use debian (linux) would that work and If so how????

thanks for the help
bahabryra

**Comment by bahabryra** [comment]
and this is also asking if I put shimboot into the Chromebook instead of the USB drive or SD card would it still work 

like my prev ? kinda in a way

**Comment by funkymokey** [comment]
Delete part of the internal drive's partition and use the unallocated space to keep debian

**Comment by ading2210** [comment]
What? 

Also this is the wrong place to ask.

**Comment by goober3853** [comment]
You could resize your Chrome OS partition with something like Gparted, make a new one and copy over the roots. The partition should be recognized by the Shimboot bootloader, but I can't confirm because I use Terra OS

**Comment by Fighterhen63** [comment]
Hey @bahabryra  sorry this is a bit late but yeah you could! So in shimboot the first 2 options are for chromeOS, and if your chromebook has force enrollment you could use one of those to be enrolled, this would use your internal storage and allow you to use shimboot.

**Comment by TheTruePerson** [comment]
However  when you shut down the managed os, it will say "developer mode is not allowed" along with a loud beep, depending on the chromebook. You can do esc-refresh-power and re-inset the usb to contine using, or you can just hit enter 2x on the developer mode is not allowed screen. This will force a powerwash, but will completely return your device to normal.

**Comment by bahabryra** [comment]
thx so much

-- 

sent from email
