### ISSUE TITLE
ASUS CM3001 boot fails with "failed to configure device mapper root"

### ISSUE THREAD

**Issue by cpucat** [ading2210/shimboot#205]
**Describe the bug**
Instead of booting, shimboot throws an error and fails to start after I built it for an ARM Chromebook

**To Reproduce**
1. Download the RMA shim from https://www.asus.com/us/laptops/for-home/Chromebook/asus-chromebook-cm30-detachable-cm3001/helpdesk_download?model2Name=ASUS-Chromebook-CM30-Detachable-CM3001
2. Extract the shim somewhere
3. Edit build_complete.sh to recognize the board name and take the extracted shim instead of trying to download it's own (for refrence, the git diff for my edit is pasted below)
```
diff --git a/home/cpucat/Downloads/build_complete.sh b/home/cpucat/Desktop/shimboot/build_complete.sh
old mode 100644
new mode 100755
index c02e3d2..253c072
--- a/home/cpucat/Downloads/build_complete.sh
+++ b/home/cpucat/Desktop/shimboot/build_complete.sh
@@ -37,7 +37,7 @@ distro="${args['distro']-debian}"
 arm_boards="
   corsola hana jacuzzi kukui strongbad nyan-big kevin bob
   veyron-speedy veyron-jerry veyron-minnie scarlet elm
-  kukui peach-pi peach-pit stumpy daisy-spring trogdor
+  kukui peach-pi peach-pit stumpy daisy-spring trogdor staryu
 "
 #a list of shims that have a patch for the sh1mmer vulnerability
 bad_boards="reef sand snappy pyro"
@@ -121,8 +121,8 @@ print(reco_url)
 ' $board)"
 print_info "found url: $reco_url"
 
-shim_bin="$data_dir/shim_$board.bin"
-shim_zip="$data_dir/shim_$board.zip"
+shim_bin="~/Desktop/rma.bin"
+shim_zip=""
 reco_bin="$data_dir/reco_$board.bin"
 reco_zip="$data_dir/reco_$board.zip"
 mkdir -p "$data_dir"
@@ -163,8 +163,7 @@ retry_cmd() {
 print_title "downloading recovery image"
 download_and_unzip $reco_url $reco_zip $reco_bin
 
-print_title "downloading shim image"
-download_and_unzip $shim_url $shim_zip $shim_bin
+print_title "using HAX... shim image"
```
4. Write patched image to a USB drive
5. Plug USB into an USB-C dock and boot the laptop off of it
6. See error

**Expected behavior**
Shimboot to mount the USB drive and boot to the desktop

**Screenshots / Photos**
![IMG_20241226_083321721_HDR.jpg](https://github.com/user-attachments/assets/a84d0092-ed1d-4e49-aaa2-1a1a065b399f)

**Target Chrome OS Device (please complete the following information):**
 - Board Name: Staryu
 - Device Name: Starmie
 - Shimboot version (e.g. v1.0.1) 

**Build Device:**
 - OS: Debian 12
 - Neofetch out:
```
cpucat@shimmer-hplaptop14cf2xxx 
------------------------------- 
OS: Debian GNU/Linux 12 (bookworm) x86_64 
Host: HP Laptop 14-cf2xxx 
Kernel: 6.1.0-27-amd64 
Uptime: 5 days, 1 hour, 14 mins 
Packages: 2848 (dpkg) 
Shell: bash 5.2.15 
Resolution: 1366x768 
DE: Plasma 5.27.5 
WM: KWin 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze [GTK2/3] 
Terminal: konsole 
CPU: Intel Celeron N4120 (4) @ 2.600GHz 
GPU: Intel GeminiLake [UHD Graphics 600] 
Memory: 2374MiB / 3677MiB 
```

**Comment by cpucat** [comment]
I forgot to attach the log files from the boot drive, here they are: (filetype changed to .txt so that I could upload them)
[dmesg.txt](https://github.com/user-attachments/files/18254267/dmesg.txt)
[factory_initramfs.log.txt](https://github.com/user-attachments/files/18254268/factory_initramfs.log.txt)

**Comment by ading2210** [comment]
Shimboot requires a vulnerability (sh1mmer) to work at all. This vulnerability was patched in early 2023 so devices released after this time will never be able to boot modified shims. Thus, it's impossible for this to work with RMA shims on your device. If you look at https://chrome100.dev/board/staryu, the only Chrome OS releases for this device were after December 2023 so it's too new. 

Theoretically it's possible to use a modified recovery image rather than a shim, but this requires actual dev mode (so impossible on enrolled devices), and it's something that's unimplemented currently.

**Comment by cpucat** [comment]
Sweet, the problem is that I'm an idiot 


Thanks
