### ISSUE TITLE
Device compatibility report for: Dell Chromebook 11 3189/3180 (Kefka)

### ISSUE THREAD

**Issue by ZeglolTheThirtySixth** [ading2210/shimboot#22]
**Compatibility Info**:
- Board Name: Kefka
- X11: No (Kernel too old)
- Wifi: Yes
- Internal Audio: Yes
- Backlight: Yes
- Touchscreen: Untested
- 3D acceleration: No
- Bluetooth: untested
- Webcam: untested

**Comment by NotDarkn** [comment]
nice

**Comment by ading2210** [comment]
Thanks for the report.

Could you send the contents of `/var/log/Xorg.0.log` by any chance? It would be nice to get X11 working on these older boards.

**Comment by ZeglolTheThirtySixth** [comment]
Yeah, i'll rebuild and get them sometime soon
