### ISSUE TITLE
build_complete.sh: IndexError: list index out of range (nissa)

### ISSUE THREAD

**Issue by NotDarkn** [ading2210/shimboot#24]
**Describe the bug**
When building for `nissa` using the `build_complete.sh` script, the following error appears for both in a virtual machine and a GitHub workflow:
```
File "<string>", line 9, in <module>
IndexError: list index out of range
```

**To Reproduce**
1. Clone the repository, or fork the repository.
2. Run `sudo ./build_complete.sh nissa`
   - Or if by a GitHub workflow, make a commit or run it manually 
      - (change the workflow first to allow it to run manually)
3. Wait a few seconds and it'll report the same issue I listed.

**Expected behavior**
To proceed like usual just like any other board, such as `octopus` or `dedede`.

**Screenshots / Photos**
![image](https://github.com/ading2210/shimboot/assets/73033672/2738f24e-2805-43c6-8dad-b4e2f44ed2a0)
![image](https://github.com/ading2210/shimboot/assets/73033672/1439128f-01e0-4bd6-aacf-a93556e302b5)

**Target Chrome OS Device (please complete the following information):**
 - Board Name: nissa
 - Device Name: N/A
 - Shimboot version: N/A (latest commit)

**Build Device (please complete the following information):**
 - OS: Debian 12
 - Neofetch stdout:
![image](https://github.com/ading2210/shimboot/assets/73033672/fdfd25f1-e5da-420d-b663-8882176262e5)

**Additional Information:**
Building a `nissa` shimboot image manually does work as intended, so if I had to guess: Due to the recent changes that chrome100 has made, `nissa` may be broken in the recovery image list in some way or another? This is speculation and I could be completely wrong.

**Comment by ading2210** [comment]
What does passing `DEBUG=1` to the build script give you? (`sudo DEBUG=1 ./build_complete.sh`)

**Comment by NotDarkn** [comment]
> What does passing `DEBUG=1` to the build script give you? (`sudo DEBUG=1 ./build_complete.sh`)

https://github.com/ading2210/shimboot/assets/73033672/aff17d60-8f58-4b33-ac9b-77a35fcb379f

**Comment by ading2210** [comment]
It looks like on some nissa devices the Chromium serving builds API isn't returning any recovery images.
![image](https://github.com/ading2210/shimboot/assets/71154407/ddf18258-87cf-4216-ac56-d3a6897b8ca5)

**Comment by ading2210** [comment]
This is fixed in the latest commit.
