### ISSUE TITLE
Kernel update???

### ISSUE THREAD

**Issue by UnicycleParrot** [ading2210/shimboot#27]
Is it possible to update kernel on these shimboot prebuilt images?
I am relatively new to linux, so i do not totally understand the process for updating the kernel.

My board is dedede

Here is what neofetch says.

OS: Debian GNU/Linux 12 (bookworm) on Chrome OS x 
Host: Drawcia rev7 
Kernel: 5.4.85-22138-ga9994f5cad40 
Uptime: 5 mins 
Packages: 1475 (dpkg) 
Shell: bash 5.2.15 
Resolution: 1366x768 
DE: Xfce 4.18 
WM: Xfwm4 
WM Theme: Default 
Theme: Adwaita-dark [GTK2/3] 
Icons: Tango [GTK2], Adwaita [GTK3] 
Terminal: xfce4-terminal 
Terminal Font: Monospace 12 
CPU: Intel Celeron N5100 (4) @ 2.800GHz 
GPU: Intel JasperLake [UHD Graphics] 
Memory: 874MiB / 7817MiB 

From my research, linux kernel 5.4, which appears to be what i have is from late 2019.

**Comment by ading2210** [comment]
It's not possible, since the shim's kernel is signed by Google and won't boot if modified.

**Comment by FoxYolk** [comment]
damn it. for those trying to use nftables/vpns you can just use openvpn with a config directly, instead of using the vpn client. (worked for me for mullvad)
