### ISSUE TITLE
Device compatibility report for: Zork

### ISSUE THREAD

**Issue by bruhderek** [ading2210/shimboot#28]
**Compatibility Info**:
- Board Name: zork
- X11: untested
- Wifi: yes
- Internal Audio: no
- Backlight: untested
- Touchscreen: yes
- 3D acceleration: yes
- Bluetooth: yes
- Webcam: yes

**Other Notes:**:
- There is no backlight

**Comment by ading2210** [comment]
Wdym by `X11: untested`? X11 is what handles the display so if the GUI showed at all then it worked.

**Comment by NotDarkn** [comment]
> Wdym by `X11: untested`? X11 is what handles the display so if the GUI showed at all then it worked.

probably didn't know what you meant by X11
![image](https://github.com/ading2210/shimboot/assets/73033672/67323da3-59cc-4c05-937f-464593e58cdf)

**Comment by bruhderek** [comment]
? X11 is not wayland (which kde uses)
