### ISSUE TITLE
How to build Kali distribution?

### ISSUE THREAD

**Issue by LavedenC1** [ading2210/shimboot#29]
Hello, can someone please give me step by step on how to build Kali Linux .img?

**Comment by LavedenC1** [comment]
A Kali shimboot img

**Comment by ading2210** [comment]
I won't be supporting Kali Linux in Shimboot.

**Comment by LavedenC1** [comment]
Ok, what I meant is in the FAQ, it says you can build your own distro, if you apply the proper system patches and so on.

**Comment by LavedenC1** [comment]
How do I do that?

**Comment by LavedenC1** [comment]
I know but it says I can build any distro in FAQ.

**Comment by LavedenC1** [comment]
I don't understand the instructions though.
