### ISSUE TITLE
Device compatibility report for: GRUNT

### ISSUE THREAD

**Issue by NotDarkn** [ading2210/shimboot#30]
## Compatibility Info
- **Board Name**: grunt
- **X11**: yes
- **Wifi**: yes
- **Internal Audio**: no
- **Backlight**: yes
- **Touchscreen**: yes
- **3D acceleration**: yes
- **Bluetooth**: yes
- **Webcam**: yes

## Other Notes
Source: Gabe6out - 836229423433908275

![compatibility info](https://github.com/ading2210/shimboot/assets/73033672/82dea12b-dc3d-4a33-ace4-c8cbff39e683)
![x11 compatibility](https://github.com/ading2210/shimboot/assets/73033672/7f508b1c-456e-4f28-81ef-4bc0f548f138)
![camera compatbility](https://github.com/ading2210/shimboot/assets/73033672/006d8d0d-9d6c-43e0-a0c3-b03ce8a0e6c7)

**Comment by ading2210** [comment]
I just added this to the readme.
