### ISSUE TITLE
"llvmpipe" renderer being used instead of GPU accelerated rendering, Debian 12 (octopus)

### ISSUE THREAD

**Issue by 02tz** [ading2210/shimboot#32]
**Describe the bug**
As the title explains, Debian Bookworm is using the llvmpipe renderer by default, and this causes software to experience heavy stutters and framedrops. Various attempts to enable hardware rendering have failed.

**To Reproduce**
1. Run graphics intensive app (firefox, steam)
2. Play video or scroll through element heavy page
3. Lag and tearing is seen

**Expected behavior**
Hardware rendering is used and graphics aren't hellishly slow

**Screenshots / Photos**
inxi -G Output: 
`user@shimboot-octopus:~$ inxi -G
Graphics:
  Device-1: Intel GeminiLake [UHD Graphics 600] driver: i915 v: kernel
  Device-2: Luxvisions Innotech EasyCamera 1M type: USB driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 22.1.9 driver: X:
    loaded: modesetting dri: swrast gpu: i915 resolution: 1366x768~60Hz
  API: OpenGL v: 4.5 Mesa 22.3.6 renderer: llvmpipe (LLVM 15.0.6 128 bits)
`

Output of "glxinfo | grep OpenGL"

**user@shimboot-octopus:~$ glxinfo | grep OpenGL
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 15.0.6, 128 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 22.3.6
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5 (Compatibility Profile) Mesa 22.3.6
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:**

Configuration: /etc/X11/xorg.conf.d/20-intel.conf 

**Section "Device"
   Identifier  "Intel Graphics"
   Driver      "modesetting"
   Option      "AccelMethod"  "sna"
EndSection**

Output of neofetch
`user@shimboot-octopus:~$ neofetch

user@shimboot-octopus 
-----
OS: Debian GNU/Linux 12 (bookworm) on Chrome OS x 
Host: Phaser rev5 
Kernel: 4.14.91-18023-g2ab161c540baf 
Uptime: 9 mins 
Packages: 2192 (
Shell: bash 5.2.15 
Resolution: 
DE: Xfce 4.18 
WM: 
WM Theme: Default 
Theme: Adwaita-dark [GTK2/3] 
Icons: Tango [GTK2], Adwaita [GTK3] 
Terminal: xfce4-terminal 
Terminal Font: Monospace 12 
CPU: Intel Celeron N4120 (4) @ 2.600GHz 
GPU: Intel GeminiLake [UHD Graphics 600] 
Memory: 1690MiB / 3805MiB 
`

**Target Chrome OS Device (please complete the following information):**
 - Board Name: octopus
 - Device Name: PHASER360
 - Shimboot version v1.0.2

**Comment by 02tz** [comment]
lmao codeblock fail

**Comment by ading2210** [comment]
Have you tried the steps suggested in the README? https://github.com/ading2210/shimboot?tab=readme-ov-file#gpu-acceleration-isnt-working-how-can-i-fix-this

**Comment by ading2210** [comment]
Also, it would be helpful for you to send the contents of your Xorg.0.log file at `/var/log/Xorg.0.log`

**Comment by 02tz** [comment]
> Have you tried the steps suggested in the README? https://github.com/ading2210/shimboot?tab=readme-ov-file#gpu-acceleration-isnt-working-how-can-i-fix-this

Yes, and I have also tried installing non-free drivers and firmware to no avail.

> Also, it would be helpful for you to send the contents of your Xorg.0.log file at /var/log/Xorg.0.log

[Xorg.0.log](https://github.com/user-attachments/files/15782564/Xorg.0.log)

**Comment by 02tz** [comment]
Sorry if I include irrelevant or insufficient information, I don't know too much about xorg. (or the real issue at hand)

**Comment by 02tz** [comment]
It seems setting the driver from "modesetting" to "intel" in `/etc/X11/xorg.conf.d/20-intel.conf` has fixed the issue even if it is not directly stated with `inxi -G`. There is no lags in Chromium and KVM, my ChromeOS Flex virtual machine runs flawlessly now and Thorium is faster than ever. Closed?

**Comment by adhdkiddy** [comment]
I think this is happening only on octopus, and more specifically phaser, since i have the same board as this person and 3d accel doesnt work

**Comment by adhdkiddy** [comment]
im just guessing

**Comment by Ethan-Mulwee** [comment]
I'm having the same issue on an octopus board and phaser model as well. Managed to get it working by setting up the xorg 20-intel.conf file and following the instructions for using mesa-amber.

**Comment by Ethan-Mulwee** [comment]
> There isn't any /etc/X11/xorg.conf.d/20-intel.conf line, it stops at xorg.conf.d as it is empty. Do I have to add my own .conf file and then add the configuration mentioned in the issue? I never realized ive been using shimboot without gpu accel. No wonder Geometry Dash ran at 20 fps idle.

Yes you created the config file. I don't think I used the exact config in this post but something similar. Be careful messing around the with xorg config if you aren't used to it though it's pretty easy to break something.

**Comment by Ethan-Mulwee** [comment]
> > Yes you create the config file. I don't think I used the exact config in this post but something similar. Be careful messing around the with xorg config if you aren't used to it though it's pretty easy to break something.
> 
> Well could you send me your conf file? Or at least a template?

I don't have that system anymore but I believe this was a config file I used

Section “Device”
      Identifier “Intel Graphics”
      Driver “Intel”
      Option “DRI” “3”
EndSection

**Comment by diogodiogo2** [comment]
For me, Wayland worked from the start with KDE (after the commands suggested in github), but X11 used llvmpipe. To fix X11, here's the 20-intel.conf I used (a bit different than the one posted previously):
```
Section "Device"
    Identifier  "Intel Graphics"
    Driver      "intel"
    Option      "AccelMethod" "uxa"
    Option      "DRI" "2"
EndSection
```

**Comment by ading2210** [comment]
@diogodiogo2 Did you use the mesa-amber drivers?

**Comment by diogodiogo2** [comment]
> [@diogodiogo2](https://github.com/diogodiogo2) Did you use the mesa-amber drivers?

Yes, not sure if they're needed but I had already installed them.
