### ISSUE TITLE
Expanding storage (on octopus)

### ISSUE THREAD

**Issue by lcguts** [ading2210/shimboot#33]
**Compatibility Info**:
- Board Name: (e.g. octopus)
- X11: /untested 
- Wifi: yes
- Internal Audio: yes
- Backlight: yes
- Touchscreen: untested
- 3D acceleration: untested 
- Bluetooth: untested
- Webcam: untested

Hello guys! When I tried to install/update things, I was unable to, since there was very little space left, even in a bigger drive (SD Card). The first thing we tried on was a usb flash drive that, except from being slower than the sd card we tested later, gave the same results as the sd card. The flash drive has 16GB of storage and the sd card has 32. So how do we expand our storage, to do actual stuff on it?

**Comment by ading2210** [comment]
Read the instructions in the README please.
