### ISSUE TITLE
Booting into Debian

### ISSUE THREAD

**Issue by Fighterhen63** [ading2210/shimboot#43]
Hi! I have been using TerraOS but decided I wanted to try this, but I cannot figure out how to boot. I have used a pre built image for dedede (the latest one) and when I boot into it, it brings me to a shimmer screen with options. I have tried using the exec command which works but then it gives me new options and when I put anything in it gives me invald option selected. What do I do?

Thanks!

**Comment by ading2210** [comment]
Type "3" (option 3 is debian) and hit enter.

**Comment by Fighterhen63** [comment]
> Type "3" (option 3 is debian) and hit enter.

This is what happens 
![17215568338926706590799443489112](https://github.com/user-attachments/assets/ca79e45e-66ee-4dfc-ba75-510866f2f3a6)

**Comment by Fighterhen63** [comment]
@ading2210 Please Help I

**Comment by ading2210** [comment]
Oh that's strange and definitely not right. Can you select "s" to enter a shell, then send a photo of the output of `fdisk -l`?

**Comment by Fighterhen63** [comment]
> Oh that's strange and definitely not right. Can you select "s" to enter a shell, then send a photo of the output of `fdisk -l`?

I fixed it. So what happened was I ran the image through a shim builder bc that's what I've done for everything else but just using the regular bin fixed it sorry to bother you!

**Comment by Fighterhen63** [comment]
@ading2210 One last question I understand that you have this in the readme but I have no idea what my block device is to expand my storage. I'm using a dedede device with a sd card running this. What could be my replacement for sdX4?

**Comment by Fighterhen63** [comment]
@ading2210 Please Help🙏

**Comment by ading2210** [comment]
Run `findmnt -T /` and it will tell you.

**Comment by Fighterhen63** [comment]
> Run `findmnt -T /` and it will tell you.

@ading2210 Getting this error
![Uploading 17217054935956045554877381776358.jpg…]()

**Comment by ading2210** [comment]
Your photo wasn't uploaded properly. I'm not able to view it.

**Comment by Fighterhen63** [comment]
> Your photo wasn't uploaded properly. I'm not able to view it.

@ading2210 
![17217067365638613728372025687491](https://github.com/user-attachments/assets/5f865700-cfb2-4e04-8a6f-a73b990f12fa)

**Comment by ading2210** [comment]
Run `sudo growpart /dev/mmcblk0`. Note that the `p4` at the end is omitted.

**Comment by Fighterhen63** [comment]
> Run `sudo growpart /dev/mmcblk0 4`. Note that the `p4` at the end is omitted.

@ading2210 That worked but only gave me about 100 mb

**Comment by ading2210** [comment]
Did you run `resize2fs` like the instructions say?

**Comment by Fighterhen63** [comment]
> Did you run `resize2fs` like the instructions say?

@ading2210 Yes this is what I just got
![17217084472756298857129040895403](https://github.com/user-attachments/assets/516b1626-4bfc-4c1d-b716-0534d200da0f)

**Comment by Fighterhen63** [comment]
> > Did you run `resize2fs` like the instructions say?
> 
> @ading2210 Yes this is what I just got ![17217084472756298857129040895403](https://private-user-images.githubusercontent.com/133062458/351184424-516b1626-4bfc-4c1d-b716-0534d200da0f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MDk4MjQsIm5iZiI6MTcyMTcwOTUyNCwicGF0aCI6Ii8xMzMwNjI0NTgvMzUxMTg0NDI0LTUxNmIxNjI2LTRiZmMtNGMxZC1iNzE2LTA1MzRkMjAwZGEwZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwNDM4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTFjMDQ2ZTI5NThkZmEwZDAyYzY1ZjJhZmY4Yzg4NmJkYjcyODA5NTdmMzEwZTcyYmNlYTY1YTEwMDEwZmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TYQ7CfBDtdOZSoVBBn6I5IUfnglnqWlHvDI246LogJg)

@ading2210 is there any fix?

**Comment by ading2210** [comment]
Use `/dev/mmcblk0p4` for the resize2fs command.

**Comment by Fighterhen63** [comment]
> Use `/dev/mmcblk0p4` for the resize2fs command.

@ading2210 Thank you so much! That worked!

**Comment by Fighterhen63** [comment]
@ading2210 Is there anyway so when I close my computer it doesn't shut it down?

**Comment by Fighterhen63** [comment]
> @ading2210 Yes for the resize. Also why the heck do my files keep locking ![17217261489802707791922250254067](https://private-user-images.githubusercontent.com/133062458/351265332-f2dd29e0-836b-4042-b135-f8f16ebd7dad.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMDcwMDIsIm5iZiI6MTcyMjEwNjcwMiwicGF0aCI6Ii8xMzMwNjI0NTgvMzUxMjY1MzMyLWYyZGQyOWUwLTgzNmItNDA0Mi1iMTM1LWY4ZjE2ZWJkN2RhZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QxODU4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjhkMTAzYjEyZDUzZTcyNGJhZTZmYmMxNDYwN2FiZWJmYTQyNzk0NWViZDRiYWIyZTViYzc5Mzg2ZGMyMjQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._AVaOOqy4TxINU3IZKnsC0MRmHYHgw3E1WH7rhJdcXE)

@ading2210 I'm still having this happen and idk why. Do you know why?

**Comment by Fighterhen63** [comment]
@ading2210 I'm sorry but my last comment is still like breaking this, could you help me on why it's happening?

**Comment by Fighterhen63** [comment]
@ading2210 Please help me, this problems getting really annoying.

**Comment by OtterCodes101** [comment]
bro jiggled his usb too hard

**Comment by Fighterhen63** [comment]
> bro jiggled his usb too hard

I'm using a sd card.
