### ISSUE TITLE
How would I go about updating the shimboot bootloader?

### ISSUE THREAD

**Issue by Xanderplayz16** [ading2210/shimboot#49]
I don't mean debian, I mean the shimboot bootloader. I am on version 1.1.0, and I want to upgrade to version 1.1.1. How would I do that? Should I just replace all the partitions (except the one containing the OS) or do something else?

**Comment by Xanderplayz16** [comment]
> Yep, replacing the bootloader partition would work fine. A dedicated updater tool would be nice to have though.

Thanks!

**Comment by Fighterhen63** [comment]
@Xanderplayz16 When I do dd if=/dev/mapper/loop0p4 of=/dev/mmcblk0 all it does is go to a new line and freeze. Is there a fix?

**Comment by OtterCodes101** [comment]
add status=progress to actually show progress(dd by default doesn't output anything)
