### ISSUE TITLE
Failed to mount USB!

### ISSUE THREAD

**Issue by Fighterhen63** [ading2210/shimboot#50]
Hi I'm using a dedede pre built and it was running fine but not it's hitting me with this error  (See picture)
![IMG_20240820_111938](https://github.com/user-attachments/assets/a699c5d2-91af-4a14-9ae1-c5ba2e7282f9)

**Comment by Fighterhen63** [comment]
> Hi I'm using a dedede pre built and it was running fine but not it's hitting me with this error (See picture) ![IMG_20240820_111938](https://private-user-images.githubusercontent.com/133062458/359561036-a699c5d2-91af-4a14-9ae1-c5ba2e7282f9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzExNTYsIm5iZiI6MTcyNDE3MDg1NiwicGF0aCI6Ii8xMzMwNjI0NTgvMzU5NTYxMDM2LWE2OTljNWQyLTkxYWYtNGExNC05YWUxLWM1YmEyZTcyODJmOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQxNjIwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTIwNmIwMjllOGM1YmVjN2E1YmU3NjNiNDZmZWRhZDQxZWYyZjM4NTA4ODQzOTczYjM5OTExY2YxY2Y0M2ZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Rmg5Po8oDAK8ZWXrAZbnv01JsEGs6AMtd7edGytGFJ8)

Better image:
![IMG_20240820_112327](https://github.com/user-attachments/assets/f3532115-4801-4c4f-9a9f-980963026e22)

**Comment by ading2210** [comment]
Try using a USB drive instead of an SD card. The error you're seeing is a bug with the shim's initramfs, which cannot be modified.

**Comment by ading2210** [comment]
This also might be related to #44

**Comment by ading2210** [comment]
You probably have a failing SD card then.

**Comment by Fighterhen63** [comment]
@ading2210 Also for some reason now when I login it just sends me back to the login screen like I didn't just login. Is there a fix?

**Comment by ading2210** [comment]
That happens when you run out of disk space due to forgetting to expand the disk. Refer to this part of the instructions to fix it:
> Expand the rootfs partition so that it fills up the entire disk by running sudo growpart /dev/sdX 4 (replacing sdX with the block device corresponding to your disk) to expand the partition, then running sudo resize2fs /dev/sdX4 to expand the filesystem.

**Comment by Fighterhen63** [comment]
> That happens when you run out of disk space due to forgetting to expand the disk. Refer to this part of the instructions to fix it:
> 
> > Expand the rootfs partition so that it fills up the entire disk by running `sudo growpart /dev/sdX` 4 (replacing sdX with the block device corresponding to your disk) to expand the partition, then running `sudo resize2fs /dev/sdX4` to expand the filesystem.

I have 56 gib of storage still

**Comment by Fighterhen63** [comment]
Also Would I have to reformat  the sdcard?

**Comment by Fighterhen63** [comment]
> > That happens when you run out of disk space due to forgetting to expand the disk. Refer to this part of the instructions to fix it:
> > > Expand the rootfs partition so that it fills up the entire disk by running `sudo growpart /dev/sdX` 4 (replacing sdX with the block device corresponding to your disk) to expand the partition, then running `sudo resize2fs /dev/sdX4` to expand the filesystem.
> 
> I have 44 gib of storage still according to my other computer ![image](https://private-user-images.githubusercontent.com/133062458/360085840-a1e82426-05dd-42df-b04a-528164768c23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNzI0NzQsIm5iZiI6MTcyNDI3MjE3NCwicGF0aCI6Ii8xMzMwNjI0NTgvMzYwMDg1ODQwLWExZTgyNDI2LTA1ZGQtNDJkZi1iMDRhLTUyODE2NDc2OGMyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQyMDI5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWVjZWJhMzAxMGM1YWMwODNlNDZjODYxMWQ1NmQ1MTQzZWI5MzI4YTUwMjFmN2NkNzRlMzk2MDI3Y2MxYjJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m3b8VNlrU9_UHCDuY35gcdmSv02SxxpOer5cfvEVmOE)



> That happens when you run out of disk space due to forgetting to expand the disk. Refer to this part of the instructions to fix it:
> 
> > Expand the rootfs partition so that it fills up the entire disk by running `sudo growpart /dev/sdX` 4 (replacing sdX with the block device corresponding to your disk) to expand the partition, then running `sudo resize2fs /dev/sdX4` to expand the filesystem.

@ading2210  Also I can't even get into a terminal so how would I run it

**Comment by Fighterhen63** [comment]
@ading2210 If you cannot answer those just lmk but one last thing what format should my sd card be in anyway? I've been formatting it to FAT 32 maybe thats an issue?

**Comment by Fighterhen63** [comment]
@ading2210  I figured out the issue which is very strange but is going to  be SUPER useful for everyone else. So when creating these images they have everything installed, but if you try to use   like curseforge or prismlauncher or like anything that requires fuse people will run "sudo apt install fuse" which will run the file sure but when you restart you have now lost essential files that  runs your desktop. So yeah theres the fix. Don't do that.

**Comment by kkilobyte** [comment]
> > > That happens when you run out of disk space due to forgetting to expand the disk. Refer to this part of the instructions to fix it:
> > > > Expand the rootfs partition so that it fills up the entire disk by running `sudo growpart /dev/sdX` 4 (replacing sdX with the block device corresponding to your disk) to expand the partition, then running `sudo resize2fs /dev/sdX4` to expand the filesystem.
> > 
> > I have 44 gib of storage still according to my other computer ![image](https://private-user-images.githubusercontent.com/133062458/360085840-a1e82426-05dd-42df-b04a-528164768c23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNzI0NzQsIm5iZiI6MTcyNDI3MjE3NCwicGF0aCI6Ii8xMzMwNjI0NTgvMzYwMDg1ODQwLWExZTgyNDI2LTA1ZGQtNDJkZi1iMDRhLTUyODE2NDc2OGMyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQyMDI5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWVjZWJhMzAxMGM1YWMwODNlNDZjODYxMWQ1NmQ1MTQzZWI5MzI4YTUwMjFmN2NkNzRlMzk2MDI3Y2MxYjJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m3b8VNlrU9_UHCDuY35gcdmSv02SxxpOer5cfvEVmOE)
> 
> 
> 
> > That happens when you run out of disk space due to forgetting to expand the disk. Refer to this part of the instructions to fix it:
> > 
> > > Expand the rootfs partition so that it fills up the entire disk by running `sudo growpart /dev/sdX` 4 (replacing sdX with the block device corresponding to your disk) to expand the partition, then running `sudo resize2fs /dev/sdX4` to expand the filesystem.
> 
> @ading2210  Also I can't even get into a terminal so how would I run it

reflash the image, login as root, and run it

**Comment by Fighterhen63** [comment]
> > > > That happens when you run out of disk space due to forgetting to expand the disk. Refer to this part of the instructions to fix it:
> > > > > Expand the rootfs partition so that it fills up the entire disk by running `sudo growpart /dev/sdX` 4 (replacing sdX with the block device corresponding to your disk) to expand the partition, then running `sudo resize2fs /dev/sdX4` to expand the filesystem.
> > > 
> > > 
> > > I have 44 gib of storage still according to my other computer ![image](https://private-user-images.githubusercontent.com/133062458/360085840-a1e82426-05dd-42df-b04a-528164768c23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNzI0NzQsIm5iZiI6MTcyNDI3MjE3NCwicGF0aCI6Ii8xMzMwNjI0NTgvMzYwMDg1ODQwLWExZTgyNDI2LTA1ZGQtNDJkZi1iMDRhLTUyODE2NDc2OGMyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQyMDI5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWVjZWJhMzAxMGM1YWMwODNlNDZjODYxMWQ1NmQ1MTQzZWI5MzI4YTUwMjFmN2NkNzRlMzk2MDI3Y2MxYjJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m3b8VNlrU9_UHCDuY35gcdmSv02SxxpOer5cfvEVmOE)
> > 
> > 
> > > That happens when you run out of disk space due to forgetting to expand the disk. Refer to this part of the instructions to fix it:
> > > > Expand the rootfs partition so that it fills up the entire disk by running `sudo growpart /dev/sdX` 4 (replacing sdX with the block device corresponding to your disk) to expand the partition, then running `sudo resize2fs /dev/sdX4` to expand the filesystem.
> > 
> > 
> > @ading2210  Also I can't even get into a terminal so how would I run it
> 
> reflash the image, login as root, and run it

@kkilobyte Do you know of anyway of doing this without wiping everything?
