### ISSUE TITLE
Booting Faliure. 

### ISSUE THREAD

**Issue by Fighterhen63** [ading2210/shimboot#53]
Hello once again. This has happened a few times, and thought i'd bring it to attention. When I type in 3 and push enter the screen shows the first two lines and then shuts off and reboots to the recovery screen. Is this a known issue? This happens very occasinally, but it just happened again and before I wipe everything just want to make sure its something I might be able to fix.

**Comment by Fighterhen63** [comment]
Edit: After looking at the sd card it appears that everything got deleted somehow 
![image](https://github.com/user-attachments/assets/0a6bedf3-5241-4bef-9a30-4b7f4498681f)

**Comment by Fighterhen63** [comment]
> Edit: After looking at the sd card it appears that everything got deleted somehow ![image](https://private-user-images.githubusercontent.com/133062458/361562189-0a6bedf3-5241-4bef-9a30-4b7f4498681f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MTAzNTksIm5iZiI6MTcyNDcxMDA1OSwicGF0aCI6Ii8xMzMwNjI0NTgvMzYxNTYyMTg5LTBhNmJlZGYzLTUyNDEtNGJlZi05YTMwLTRiN2Y0NDk4NjgxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQyMjA3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzBmMzFiZTNlZjI1MTU4Yjk2MDU1NTM2OTYyYjMwMWUyNDI4ZGY1MmFhYjQyZDk1NjkwZGUyNTM0ZTJiNTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kyISGIFkMBw7TtulcptncRoFwpuLlX6VExhSLvt7HY8)

Another update, now I cannot format my SD Card at all, chrome recovery tool, commands. Dang.

**Comment by LavedenC1** [comment]
The card isn't formatted right.

**Comment by Fighterhen63** [comment]
> The card isn't formatted right.

I know that, but I cannot format it now like it just wont my Nintendo Switch cant even format it idk what to do

**Comment by LavedenC1** [comment]
What is your chrome version?

**Comment by Fighterhen63** [comment]
> What is your chrome version?

108 but im using a fully updated version of the chrome recovery tool

**Comment by LavedenC1** [comment]
Also why can't you format it?

**Comment by Fighterhen63** [comment]
> Also why can't you format it?

Not sure. It just wont let me. The recovery tool keeps giving me  a chromeos burner image error and I don't have a windows laptop and crosh is telling me its read only so I can't format it.

**Comment by Fighterhen63** [comment]
Its claiming its right protected. I've never seen that from a micro sd card

**Comment by LavedenC1** [comment]
What is your chrome version?

**Comment by Fighterhen63** [comment]
![image](https://github.com/user-attachments/assets/0606c162-9c9c-42b5-b342-0277716ca223)
![image](https://github.com/user-attachments/assets/a1f7de80-3d69-4ac5-8049-ec96713c6f01)
![image](https://github.com/user-attachments/assets/bbbaa518-f2c6-4ed0-810f-c6ba023712b8)
That last image is in crosh but in the vf2 terminal it recognizes the file system and claims its read only

**Comment by LavedenC1** [comment]
Try running df and lsusb on crosh, and tell me the results

**Comment by Fighterhen63** [comment]
![image](https://github.com/user-attachments/assets/e824cf79-26f1-4365-810b-7f75f37ff7b3)
![image](https://github.com/user-attachments/assets/9f9e90c3-6704-4020-9fa1-2ff34facdae3)

**Comment by Fighterhen63** [comment]
> Try running df on crosh, and tell me the results, and does termux have su priveledges?

Not sure let me look

**Comment by Fighterhen63** [comment]
> > Try running df on crosh, and tell me the results, and does termux have su priveledges?
> 
> No ![image](https://private-user-images.githubusercontent.com/133062458/361602737-d25881c0-00e6-41af-a2ca-3e424a42198d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MTQ5NTAsIm5iZiI6MTcyNDcxNDY1MCwicGF0aCI6Ii8xMzMwNjI0NTgvMzYxNjAyNzM3LWQyNTg4MWMwLTAwZTYtNDFhZi1hMmNhLTNlNDI0YTQyMTk4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQyMzI0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDAyMTE5N2NkMTA4YmYwNTI0ZWIwMmVlZTNkN2VkZWVmNjZiM2MwZGIxMjhhMDA4MTRiNTdhMzE2YzdiNGEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qs81aKgGYbEwXT4R_0l9mvsKoqysWlJlA7js4i3DZ-I)

Okay I did some stuff now it is root

**Comment by LavedenC1** [comment]
Run

ls /run/arc/sdcard/write/emulated

On termux as root. Tell me the output.

**Comment by Fighterhen63** [comment]
![image](https://github.com/user-attachments/assets/ca9491a8-4a6d-448c-951c-fffb834bcf11)

**Comment by LavedenC1** [comment]
Weird

**Comment by Fighterhen63** [comment]
> Weird

OH WAIT hold on

**Comment by LavedenC1** [comment]
Eject the SD cards from manager and remount it as RW

**Comment by Fighterhen63** [comment]
How?

**Comment by LavedenC1** [comment]
Before remounting it run df again.

**Comment by Fighterhen63** [comment]
![image](https://github.com/user-attachments/assets/d2ceac86-c098-4900-a73e-1103323dbdac)

**Comment by Fighterhen63** [comment]
After remounting 
![image](https://github.com/user-attachments/assets/3811fc2d-8c4b-4988-9e0d-c257aaddd021)

**Comment by LavedenC1** [comment]
Look at the last line. It wasn't there before. Try to format it now.

**Comment by Fighterhen63** [comment]
Nothing : (

**Comment by LavedenC1** [comment]
It is mounted /media/removable/USB Drive

**Comment by Fighterhen63** [comment]
Yes it is, but It won't let me format it

**Comment by Fighterhen63** [comment]
Also something else werid is I can still boot into the first menu of shimboot but nothing else besides shell

**Comment by LavedenC1** [comment]
Nothing works?

**Comment by LavedenC1** [comment]
Still can't format it?

**Comment by Fighterhen63** [comment]
> Still can't format it?

Nope. Ig my best bet is to use a windows pc at school tmrw

**Comment by LavedenC1** [comment]
Are the errors the same?

**Comment by Fighterhen63** [comment]
Yeah

**Comment by LavedenC1** [comment]
Well I tried my best.

**Comment by Fighterhen63** [comment]
> Well I tried my best.

Thanks man I appreciate it! I'll keep you updated

**Comment by LavedenC1** [comment]
One more try.
Run:
fdisk -l

As root. Send the results.

**Comment by Fighterhen63** [comment]
![image](https://github.com/user-attachments/assets/044c8475-4e10-4857-be39-9d4ee2953458)
@LavedenC1

**Comment by LavedenC1** [comment]
Run as root

umount /dev/sdc1

Send results.

**Comment by Fighterhen63** [comment]
![image](https://github.com/user-attachments/assets/3218d76e-8100-479a-8254-65abf777dc5a)
@LavedenC1

**Comment by LavedenC1** [comment]
sudo dd if=/dev/zero of=/dev/sdc bs=4M status=progress

**Comment by Fighterhen63** [comment]
![image](https://github.com/user-attachments/assets/44308751-75d3-4ae3-aaf5-7aa5ad9215e7)

**Comment by LavedenC1** [comment]
Instead of sdc try scd1

**Comment by Fighterhen63** [comment]
> Instead of sdc try sdc1

same thing

**Comment by LavedenC1** [comment]
sudo fdisk /dev/sdc

**Comment by Fighterhen63** [comment]
![image](https://github.com/user-attachments/assets/80ad34cb-d1ab-4e78-a705-42763f2a1dbf)

**Comment by Fighterhen63** [comment]
same with sdc1

**Comment by LavedenC1** [comment]
Then type d and delete the partitions. Then type w

**Comment by Fighterhen63** [comment]
> Then type d and delete the partitions. Then type w

What? Sorry im apperently illiturate tonight. Could you just give me the command

**Comment by LavedenC1** [comment]
My bad I didn't mean to type that

**Comment by LavedenC1** [comment]
Alr well there's nothing I can do about it. GGs

**Comment by ading2210** [comment]
Your SD card is failing. There's nothing I can do about it.

**Comment by Fighterhen63** [comment]
> Your SD card is failing. There's nothing I can do about it.

Trash at this point ig
