### ISSUE TITLE
Error during shimboot build

### ISSUE THREAD

**Issue by ayuruka** [ading2210/shimboot#57]
I am reporting this using translation and chatGPT as I am not able to use English.
The text is a bit strange, but please bear with me.

Describe the bug
When attempting to copy the shim kernel and extract the initramfs from the kernel, the process fails with several errors, including "No such file or directory" and "premature end of archive."

To Reproduce

Start the process of reading the shim image and copying the shim kernel.
Observe the process as it attempts to extract the initramfs.
Notice the errors appearing during the process, such as "No such file or directory" and "premature end of archive."
Expected behavior
The shim kernel should be copied successfully, and the initramfs should be extracted without errors.

Error Messages

cat: /tmp/shim_kernel/_kernel.bin.extracted/_.extracted//: No such file or directory
cpio: premature end of archive
dd: failed to open '/dev/loop0p2': No such file or directory
dd: failed to open '/dev/loop1p2': No such file or directory
dd: failed to open '/dev/loop2p2': No such file or directory
dd: failed to open '/dev/loop3p2': No such file or directory
Target Chrome OS Device

Board Name: trogdor
Device Name: pompom
Shimboot Version: 1.2.0
Build Device

OS: Ubuntu 22.04

**Comment by ading2210** [comment]
Are you using WSL? Issue #47 might be related in that case.

**Comment by ayuruka** [comment]
I'm using Ubuntu desktop.

**Comment by ading2210** [comment]
This has been fixed with commit 0fa0aa0184264ebba38497b10428a8f7f4472799 in the dev branch. Switch to the dev branch (`git clone https://github.com/ading2210/shimboot -b dev`) and try again.
