### ISSUE TITLE
Fully Unenrolled somehow 

### ISSUE THREAD

**Issue by Fighterhen63** [ading2210/shimboot#59]
Hello everyone first off for @ading2210 My SD Card was failing switching over to a Nintendo one solved everything. Second off I use both this and E-Halcyon for one reason. It allows two different chrome OS versions to be run v107 and v129. This is nice when trying to debug chrome features. But I needed to do a test for my school and decided to boot back into stable mode expecting me to need to reflash the OS instead it booted into v129 dev mode of chromeOS and with further set up found out it was fully unenrolled. I could still enroll it and it would work just fine and it kept everything apon restart but when I power washed it I was brought up with the same thing again. So somehow I've found a way to fully unenroll using those two methods combined. Take this as you will just thought I would share it.

**Comment by ading2210** [comment]
Your school probably doesn't have forced re-enrollment turned on. Shimboot does nothing special and does not attempt to change anything that might lead to unenrollment.

**Comment by Fighterhen63** [comment]
I know they do. Because I practically work for my school when it comes to
the tech department. I know we have it on. I think its booting some image
it flashed itself... Bc its on dev mode and 129 so it has to be from
something. But I thought it would be counted as a invalid image. Ig its a
mystery.
