### ISSUE TITLE
Boot Fail QR Code 

### ISSUE THREAD

**Issue by Fighterhen63** [ading2210/shimboot#61]
Hello, I just made a new image for the newest release and now whenever I boot up it is giving me a error showing me a QR Code (See image) Is there a fix?

![image](https://github.com/user-attachments/assets/6dca9a64-51f4-4069-ae21-78c1d11a5bf3)

**Comment by ading2210** [comment]
Send the output of the build script.

Also please stop deleting the issue template that asks for this kind of information.

**Comment by Fighterhen63** [comment]
My bad. 
Steps to reproduce the behavior:
1. Go to the recovery menu
2. Plug USB In 
3. Wait it will just got to the QR Code Screen

**Expected behavior**
Loads into the option menu. 

Board: DEDEDE 
OS Debian 12

OS: Debian GNU/Linux 12 (bookworm) on Chrome OS x86_64 
Host: Magolor rev7 
Kernel: 5.4.85-22138-ga9994f5cad40 
Uptime: 8 mins 
Packages: 1591 (dpkg) 
Shell: bash 5.2.15 
Resolution: 1366x768 
DE: GNOME 43.9 
WM: Mutter 
WM Theme: Fluent-Dark 
Theme: Fluent-Dark [GTK2/3] 
Icons: Win11-dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel Celeron N4500 (2) @ 2.800GHz 
GPU: Intel JasperLake [UHD Graphics] 
Memory: 2005MiB / 7817MiB 

Not sure what output you want, the terminal or is there a specific file in the folder? Thanks!

**Comment by Fighterhen63** [comment]
Also i've been using the shim_dedede.bin image should I be using the reco_dedede.bin? 
![image](https://github.com/user-attachments/assets/4da0215a-5fc5-4fd6-8b92-20150972072a)

**Comment by ading2210** [comment]
Were you flashing the `shim_dedede.bin` file to the USB?

**Comment by Fighterhen63** [comment]
@ading2210 Yes

**Comment by ading2210** [comment]
You flashed the wrong file to your USB. The correct one is named `shimboot_dedede.bin`.

**Comment by Fighterhen63** [comment]
Where is it located? After I built the image those we're the only bins I see

**Comment by Fighterhen63** [comment]
Nevermind I'm so dumb just released what I did wrong. Sorry for wasting your time... Again. Thanks for continuing to answer.

**Comment by Fighterhen63** [comment]
Like when I build the image using the command sudo ./build_complete.sh dedede desktop=gnome it just builds the two bin files I showed on the image

**Comment by Fighterhen63** [comment]
![image](https://github.com/user-attachments/assets/2dd46aa7-0776-4c3f-b261-249f95f767b6)

**Comment by Fighterhen63** [comment]
@ading2210 First off could you help me with that. More importantly second I am making a website with guides to every chromebook unenrollment method, hacks, images etc. I am making a yt channel to document the process's with videos. Can I document Shimboot? I will give proper credit ofc and not take any credit for making it and I will redirect the yt video to yours if you want if not I can create my own.
