### ISSUE TITLE
fsconfig system call failed: fuseblk: No changes allowed in reconfigure

### ISSUE THREAD

**Issue by kkilobyte** [ading2210/shimboot#65]
**Describe the bug**
When trying to make an Alpine KDE shim for `octopus`, I get the following error:
```
>> building alpine rootfs
mount: /run/media/kilo/Seagate_HDD: fsconfig system call failed: fuseblk: No changes allowed in reconfigure.
       dmesg(1) may have more information after failed mount system call.
```

**To Reproduce**
1. Run `git clone https://github.com/ading2210/shimboot`
2. Run `cd shimboot`
3. Run `sudo ./build_complete.sh octopus distro=alpine desktop=kde`
4. See error when the script tries to build the Alpine rootfs.

**Expected behavior**
The script is supposed to create a fully functional Alpine KDE shim for `octopus`.
**Screenshots / Photos**
![image](https://github.com/user-attachments/assets/4ba61031-6aac-4c4b-9ab4-b03770788867)

[Output from `sudo DEBUG=1 ./build_complete.sh`](https://github.com/user-attachments/files/16955791/build.txt)

**Target Chrome OS Device (please complete the following information):**
 - Board Name: octopus
 - Code Name: phaser360
 - Device Name: Lenovo 300e Chromebook Gen 2 (Intel)
 - Shimboot version: v1.2.1

**Build Device (please complete the following information):**
 - OS: EndeavourOS x86_64 Linux v6.10.7-arch1-1
 - neofetch --stdout
```
kilo@yaptop 
----------- 
OS: EndeavourOS Linux x86_64 
Host: 82C5 Lenovo V15-IIL 
Kernel: 6.10.7-arch1-1 
Uptime: 5 days, 1 hour, 48 mins 
Packages: 1283 (pacman), 6 (flatpak) 
Shell: fish 3.7.1 
Resolution: 1920x1080 
DE: Plasma 6.1.4 
WM: kwin 
Theme: catppuccin-mocha-mauve-standard+default [GTK2/3] 
Icons: Papirus-Dark [GTK2/3] 
Terminal: konsole 
CPU: Intel i5-1035G1 (8) @ 3.600GHz 
GPU: Intel Iris Plus Graphics G1 
Memory: 6366MiB / 19798MiB
```

**Additional context**

**Comment by kkilobyte** [comment]
Just for documentation purposes, I have tested on Celeron N4020 and N4000 varients of `octopus phaser360` (Lenovo 300e Chromebook Gen 2 (Intel)) with the same issue.

**Comment by ading2210** [comment]
Please re-run the build script with `sudo DEBUG=1 ./build_complete.sh` to show the full logs.

**Comment by kkilobyte** [comment]
@ading2210 I put a link in the original post but I'll resend the logs. 
[Output from sudo DEBUG=1 ./build_complete.sh](https://github.com/user-attachments/files/16955791/build.txt)

**Comment by kkilobyte** [comment]
Fixed the issue by trying to build on my SSD instead of my HDD, but I still get 
```
creating bind mounts for chroot
/opt/setup_rootfs_alpine.sh: line 23: setup-hostname: not found
```
[build-hostname.txt](https://github.com/user-attachments/files/16964086/build-hostname.txt)
