### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by endr1337** [ading2210/shimboot#68]
**Describe the bug**
My grunt boards debian, after web builder gives me black screen with debian cursor
**To Reproduce**
1. Go download grunt debian
3. Click on web builder
4. Scroll down to start
5. download unpatcged
6. write to sd card
7. boot
8. black screen
9. See error

**Expected behavior**
Debian loads up username screen
**Screenshots / Photos**
If applicable, add screenshots or photos to help explain your problem.

If you are reporting an issue with the build process, please run the scripts in debug mode by putting `DEBUG=1` before the build commmand, like `sudo DEBUG=1 ./build_complete.sh`.

**Target Chrome OS Device (please complete the following information):**
 - Board Name (e.g. dedede)
 - grint
 - Device Name (e.g. drawcia) 
 - i dont know
 - Shimboot version (e.g. v1.0.1) 
1.21

**Build Device (please complete the following information):**
 - OS: [e.g. Debian 12]
 - Neofetch out [run `neofetch --stdout` and paste it here]
Debian 12
**Additional context**

**Comment by kkilobyte** [comment]
There is a good chance you are being affected by the same issue @kxtzownsu had. Try constantly pressing `ctrl+alt+refresh` and `ctrl+alt+brightness up` and see if new things show up.

**Comment by endr1337** [comment]
i can see the cursor, but its just black and then it shows the login when i go into sleep mode but its frozen

**Comment by endr1337** [comment]
oh wait i logged in but its like frozen but it goes forward when i press  control alt refresh

**Comment by ading2210** [comment]
I don't know what you mean by "web builder"

There is no web builder for shimboot

**Comment by kxtzownsu** [comment]
> oh wait i logged in but its like frozen but it goes forward when i press control alt refresh

yea this is the same issue I had, not sure of the fix rn

**Comment by endr1337** [comment]
mb im tweaking i meant for sh1mmer

**Comment by endr1337** [comment]
its fixed anyhow, ctrl alt refresh and type user + tab + user and then enter and then ctrl alt refresh one more time and it works
