### ISSUE TITLE
Wifi adapter not working on HP Chromebook 11A G8 EE

### ISSUE THREAD

**Issue by endr1337** [ading2210/shimboot#69]
**Describe the bug**
the wifi interface does not show at all. drivers are all there so thats nothing to do with that. it only shows lo as the wifi interface 
**To Reproduce**
1. Go to terminal
2. type in ip link show
3.  show error

**Expected behavior**
Wifi adapter showing up
**Screenshots / Photos**
If applicable, add screenshots or photos to help explain your problem.

If you are reporting an issue with the build process, please run the scripts in debug mode by putting `DEBUG=1` before the build commmand, like `sudo DEBUG=1 ./build_complete.sh`.

**Target Chrome OS Device (please complete the following information):**
 - Board Name grunt
 - Device Name barla 
 - Shimboot version 1.2.1 

**Additional context**

**Comment by endr1337** [comment]
😭  so many things are going wrong im so sorry ading

**Comment by endr1337** [comment]
fixed! i had to get headers and then i just compiled the driver for my wifi adapter https://github.com/tomaspinho/rtl8821ce and then i just restarted Network Manager

**Comment by ading2210** [comment]
Note that if you want to get the kernel headers there are some instructions here: https://github.com/ading2210/shimboot/issues/52#issuecomment-2309071641
