### ISSUE TITLE
[HELP] Error Mounting Root-A/B

### ISSUE THREAD

**Issue by gamerbross** [ading2210/shimboot#71]
Sorry for making an issue here, probably isn't where I should make it.

I tried mounting ROOT-A in Debian, but it gives me an error:
`Error mounting /dev/mmcblk0p3 at /media/user/ROOT-A: wrong fs type, bad option, bad superblock on /dev/mmcblk0p3, missing codepage or helper program, or other error (udisks-error-quark, 0)`, also happens with ROOT-B

My board is `octopus` and my Chromebook is a `Acer Chromebook Spin 511 R752t C7lx`

**Comment by ading2210** [comment]
You need to mount it as read only. Use `sudo mount /dev/mmcblk0p3 <your_mountpoint> -o ro`.
