### ISSUE TITLE
steam says "User namespaces to be enabled" and i tried to follow the issue #12 but i dont understand it (Octopus board)

### ISSUE THREAD

**Issue by KojiCorner** [ading2210/shimboot#72]
Like i said, i dont understand what to do or anything on Issue #12. And i dont really know what to do, i have an octopus board too. I sound very stupid right now. But please help.

**Comment by Raf128** [comment]
Go to your terminal and enter "fix_bwrap". I don't understand what issue #12 has to do with this but this should fix steam.

**Comment by ading2210** [comment]
Just run `fix_bwrap` in your terminal whenever you see that error.

**Comment by KojiCorner** [comment]
Ight, thanks. That fixed it
