### ISSUE TITLE
`rescue` command creates a severe vulnerability!

### ISSUE THREAD

**Issue by SniverDaBest** [ading2210/shimboot#73]
**Describe the bug**
When going to the Shimboot OS selector, you can run rescue to boot into a "rescue" shell, before init.

**To Reproduce**
1. Go into the Shimboot os selector
2. Use the rescue command to boot into a rescue environment
3. Full root access to selected OS.

**Expected behavior**
I know this is a VERY important thing, if your OS breaks, and you need to fix it, but it gives you FULL root privileges with no password.

**Screenshots / Photos**
If applicable, add screenshots or photos to help explain your problem.

If you are reporting an issue with the build process, please run the scripts in debug mode by putting `DEBUG=1` before the build commmand, like `sudo DEBUG=1 ./build_complete.sh`.

**Target Chrome OS Device (please complete the following information):**
 - Board Name dedede
 - Device Name drawlat
 - Shimboot version v1.2.1

**Build Device (please complete the following information):**
 - OS: Debian 12
 - Neofetch out [run `neofetch --stdout` and paste it here]

**Additional context**
Maybe make it so you need a password for this?

**Comment by ading2210** [comment]
This is also the case on [any conventional Linux system](https://unix.stackexchange.com/q/34462). It is not a security issue. If your OS is unencrypted, anyone with physical access can already do whatever they want to the system.
