### ISSUE TITLE
Wifi not working on grunt

### ISSUE THREAD

**Issue by Go0gl** [ading2210/shimboot#75]
**Describe the bug**

**To Reproduce**
1. Go to 'wifi'
2. Click on 'connect thing'
4. See that there isn't anything to connect to

**Expected behavior**
To be able to connect to wireless wifi

**Screenshots / Photos**
sorry don't have any, able to take some if needed

**Target Chrome OS Device (please complete the following information):**
 - Board Name (grunt)
 - Device Name (barla)
 - Shimboot version (most recent

**Comment by Go0gl** [comment]
also,  [https://github.com/ading2210/shimboot/issues/69](url) didn't work for me

**Comment by Raf128** [comment]
what is the output of lspci

**Comment by Raf128** [comment]
i guessed that

**Comment by ading2210** [comment]
This is a duplicate of #69. Also, you do not need to sign kernel modules for them to work.
