### ISSUE TITLE
Once in dev mode cannot get out without powerwashing cb

### ISSUE THREAD

**Issue by Xoui** [ading2210/shimboot#76]
so when i restartr it, it goes to the default ur faculty doesnt support dev mode
but i dont wanna powerwash it...
what do i do?

**Comment by Xoui** [comment]
also, lets say i dont have the usb, is there anyother way to boot regular chos? (chromeos) and can i put a bootloader (grub) on the chromebooks emmc so i can boot stuff? without a total shim bc im kervner 3

**Comment by Raf128** [comment]
From what I know there is zero possible way to get into your chromeos without powerwashing. I don't think you can have another bootloader on your chromebooks storage in vanilla shimboot, but if you are a tech wizrd you could probably find a way. When you say kervner 3 wdym?

**Comment by Xoui** [comment]
wait.... Why dont i try to install mrchromebox's bios thing so i can boot into stuff... uhhh and what if i modify the code, (straight just skid it) and make 1 option to boot (il continue this tmmr)

**Comment by Raf128** [comment]
that **might** work but be extremely careful because you can easily brick your Chromebook. If you are planning on modifying the code be sure you know what you're doing.

**Comment by ading2210** [comment]
You cannot switch in and out of dev mode without powerwashing. This is by design and there is no workaround.

**Comment by OtterCodes101** [comment]
> so when i restartr it, it goes to the default ur faculty doesnt support dev mode but i dont wanna powerwash it... what do i do?

💀

**Comment by Xoui** [comment]
dawg,

**Comment by Xoui** [comment]
THEN I CANT POWERWASH MY CB EVERYTIME I WANT A UNBLOCKED  WORKsPACE

**Comment by Xoui** [comment]
THERES NO OTHER WAY FOR ME  TO UNBLOCK ANYTHING, IVE ALLREADY GOT IN TROUBLE FOR Sh1mmer, AND i have kervner 3, schools filter is on whitelisted sites

**Comment by OtterCodes101** [comment]
its literally by design that it powerwashes every time you go into devmode

**Comment by Xoui** [comment]
Then theres no point. Unless yal tell me how to unblock shit with a wl filter (i think experimental gogaurdian ai thing)
