### ISSUE TITLE
ARM-based Chromebook support 

### ISSUE THREAD

**Issue by zek-c** [ading2210/shimboot#8]
I've been monitoring this project since release and wondered, why is there no ARM device support? Is there a roadblock in the firmware or do you not plan on working with certain drivers..

**Comment by APie357** [comment]
I have an Acer R13 as a personal cb and there doesn't seem to be any shims out for it. I did manage to install archlinuxarm on it (no shims needed but idk if it will work on managed devices), but to get a graphical environment it's a lot of terminal stuff and not a lot of software is available for it. You might be able to get it to work with archlinuxarm, but not many devices are supported.

**Comment by zek-c** [comment]
linux has terminal work (mind blown) but thx

**Comment by ading2210** [comment]
ARM support is certainly possible but I don't have any devices I could test it with.

**Comment by zek-c** [comment]
buy a $50 chromebook or i'll use mine

**Comment by zek-c** [comment]
you got a status update on arm support? i can test images myself if you can trust me to do that.

**Comment by ading2210** [comment]
The main thing blocking ARM support before was that I didn't know how the extract the initramfs from the kernel images.

I investigated this a bit today and I've figured it out, so now all I need to do is automate this, then compile the needed Debian packages for ARM64.

**Comment by ading2210** [comment]
@zek-c Which board do you have? I could send you an image to test later today.

**Comment by zek-c** [comment]
I have a corsola board - codename rusty

**Comment by ading2210** [comment]
Could you try booting this image?
https://local.ading.dev/array/shimboot/corsola_test.bin

**Comment by zek-c** [comment]
yep. works nicely. ![image](https://github.com/ading2210/shimboot/assets/105883248/399995f2-e1cd-4fdd-8909-37afe61d45b7)

**Comment by ading2210** [comment]
Nice. Does booting the rootfs partitions and Chrome OS work?

**Comment by zek-c** [comment]
nope. inputting them and continuing with the prompts brings me a blank screen.

**Comment by zek-c** [comment]
but chromeos (default/3) does work.

**Comment by ading2210** [comment]
Wdym? What happens when you select the third option (default on /dev/sda4)?

**Comment by zek-c** [comment]
yes, third option boots the chromeOS dev mode bootloader. But the first two options boot a blank screen

**Comment by zek-c** [comment]
sorry i worded that one bad

**Comment by ading2210** [comment]
So that means it didn't actually work. Could you enter the shimboot shell and type `uname -a`, then send the output?

**Comment by zek-c** [comment]
ahhh, i thought /dev/sda4 was the bootloader or something. or maybe it is and you meant that the first two wouldn't boot. here's that output for ya![image](https://github.com/ading2210/shimboot/assets/105883248/08f99e92-c631-4526-943c-48e0623f63e2)
Linux localhost 5.15.74-12848-g653b187c79ae4 #2 SMP PREEMPT Tue Dec 6 19:07:10 PST 2022 aarch64 aarch64 aarch64 GNU/Linux

**Comment by ading2210** [comment]
Would it be possible for you to record a video as you try option 3? There might be an error that shows up briefly before it crashes.

**Comment by zek-c** [comment]
sure i can do that in about 10 minutes

**Comment by zek-c** [comment]
alright, all it says after entering is `selected /dev/sda4
moving mounts to newroot 
switching root` 
https://drive.google.com/file/d/1YrNaP4CXe347qsZKaViF0Owkz4mK-da-/view?usp=drivesdk
the video is still processing but it'll be done soon

**Comment by zek-c** [comment]
ok so i tried `lsblk` but its not installed to the shell, so i used fdisk -l and /dev/sda4 is the "shimboot:rootfs" so i'm just dumb

**Comment by ading2210** [comment]
I think I built the rootfs wrong on the previous test image. Try this new one:
https://local.ading.dev/array/shimboot/corsola_test2.bin

**Comment by zek-c** [comment]
sorry, i'm away rn 😭 i can test it tmrw around 4-5pm or so (we are the same time zone) or you can find someone else with a corsola to test it but i'm sorry for the inconvenience

**Comment by zek-c** [comment]
ok i've got it done, same results as last. blank screen.

**Comment by zek-c-alt** [comment]
ive currently lost access to my main account, but i will try this momentarily. (i do not have my phone at the moment and have 2fa enabled so this is from my computer)

**Comment by zek-c-alt** [comment]
ok. i did the un-csmited device and option 1 resulted in an unmanaged chromeOS. option 2 was nothing, and 3 resulted in a dev mode error beep.

**Comment by zek-c** [comment]
got my account back

**Comment by ading2210** [comment]
If booting Chrome OS worked without too much trouble its likely that regular [Devuan](https://www.devuan.org/) (fork of debian) will work just fine. I'll try building a new image with Devuan instead of making the rootfs manually which may have been flawed before.

**Comment by zek-c** [comment]
hey you got an ETA on that image? i'd try to build myself but stupid debian won't install to my software raid...😭

**Comment by zek-c** [comment]
^^bump this waiting for an update

**Comment by ading2210** [comment]
I got systemd to build correctly for arm64, and I fixed some bugs in the build script, so ARM Shimboot might work now. So far I've only built it for hana: https://local.ading.dev/array/shimboot/shimboot_hana.zip

**Comment by ading2210** [comment]
@zek-c Try this image for corsola: https://local.ading.dev/array/shimboot/shimboot_corsola.zip

**Comment by zek-c** [comment]
i have the file downloaded but had to leave for school. i'll get it done around 2pm since it's finals week so we get out earlier

**Comment by zek-c** [comment]
alright it worked. i booted into linux, i'm gonna test a few things out

**Comment by zek-c** [comment]
works nice, thanks for working this thing out :sob: 
![Screenshot_2024-06-12_23-16-07](https://github.com/ading2210/shimboot/assets/105883248/08d253b7-0d2e-4e82-b27d-41a4ebd36d7c)

**Comment by ading2210** [comment]
Does GPU acceleration and audio work?

**Comment by ading2210** [comment]
ARM support has been merged into the main branch.

**Comment by Zumwaltboi68** [comment]
@ading2210 Can you add support for Jacuzzi Boards?

**Comment by funkymokey** [comment]
Could you bring back the link? Or at least add prebuilt packages for hana?

**Comment by inquestor420** [comment]
> i need gpu acceleration on my arm chromebook bad i wanna play minecraft bro :pray: appreciate all the work tho it's working really well even without gpu accel

Yo so like I think they added it because im running sonic adventure 2 rn through flycast I'm arm aswell it's running really good also tried a bunch of games through box64 like ultrakill and they run at playable frame rates like 30 to 45 fps

**Comment by OtterCodes101** [comment]
vro whats your steam you seem like a based individual

**Comment by LukeTube1000** [comment]
I also have a ARM chromebook, could help with finding mutual support on most ARM ones. It's a Stellix as of the recovery mode, with corsola as the android name?
I know it's a MediaTek one.

**Comment by ryry-codr** [comment]
Could you bring back the corsola/rusty link because I want to do this on my Lenovo 100e Gen 4 (or If someone has that image can you send it to me please) unless the corsola image from the releases will work :/
Thanks in advance I guess?

**Comment by leahanderson1** [comment]
> Could you bring back the corsola/rusty link because I want to do this on my Lenovo 100e Gen 4 (or If someone has that image can you send it to me please) unless the corsola image from the releases will work :/ Thanks in advance I guess?

i have the same chromebook
would you want to test a kexec module for corsola/rusty

**Comment by ryry-codr** [comment]
> > Could you bring back the corsola/rusty link because I want to do this on my Lenovo 100e Gen 4 (or If someone has that image can you send it to me please) unless the corsola image from the releases will work :/ Thanks in advance I guess?
> 
> i have the same chromebook would you want to test a kexec module for corsola/rusty

if that's the only option then yeah I guess? I honestly just want to do shimboot on my chromebook and I don't really feel like testing different images and stuff

**Comment by jacobleclair** [comment]
> > Could you bring back the corsola/rusty link because I want to do this on my Lenovo 100e Gen 4 (or If someone has that image can you send it to me please) unless the corsola image from the releases will work :/ Thanks in advance I guess?
> 
> i have the same chromebook would you want to test a kexec module for corsola/rusty

still trying to get kexec working? (: 

🤞

**Comment by ryry-codr** [comment]
i tried using the like normal corsola image but it says No Valid Image Detected so i might actually test the kexec module or whatever

**Comment by leahanderson1** [comment]
> > > Could you bring back the corsola/rusty link because I want to do this on my Lenovo 100e Gen 4 (or If someone has that image can you send it to me please) unless the corsola image from the releases will work :/ Thanks in advance I guess?
> > 
> > 
> > i have the same chromebook would you want to test a kexec module for corsola/rusty
> 
> still trying to get kexec working? (:
> 
> 🤞

can someone give me the kernel version for the corsola shim i need to build my module against that and not the latest recovery kernel in order to make sure i got this working correct

**Comment by ryry-codr** [comment]
> > > > Could you bring back the corsola/rusty link because I want to do this on my Lenovo 100e Gen 4 (or If someone has that image can you send it to me please) unless the corsola image from the releases will work :/ Thanks in advance I guess?
> > > 
> > > 
> > > i have the same chromebook would you want to test a kexec module for corsola/rusty
> > 
> > 
> > still trying to get kexec working? (:
> > 🤞
> 
> can someone give me the kernel version for the corsola shim i need to build my module against that and not the latest recovery kernel in order to make sure i got this working correct

could i possibly help get that? or not

**Comment by leahanderson1** [comment]
> > > > > Could you bring back the corsola/rusty link because I want to do this on my Lenovo 100e Gen 4 (or If someone has that image can you send it to me please) unless the corsola image from the releases will work :/ Thanks in advance I guess?
> > > > 
> > > > 
> > > > i have the same chromebook would you want to test a kexec module for corsola/rusty
> > > 
> > > 
> > > still trying to get kexec working? (:
> > > 🤞
> > 
> > 
> > can someone give me the kernel version for the corsola shim i need to build my module against that and not the latest recovery kernel in order to make sure i got this working correct
> 
> could i possibly help get that? or not

yeah just run `uname -r`

**Comment by ryry-codr** [comment]
> > > > > > Could you bring back the corsola/rusty link because I want to do this on my Lenovo 100e Gen 4 (or If someone has that image can you send it to me please) unless the corsola image from the releases will work :/ Thanks in advance I guess?
> > > > > 
> > > > > 
> > > > > i have the same chromebook would you want to test a kexec module for corsola/rusty
> > > > 
> > > > 
> > > > still trying to get kexec working? (:
> > > > 🤞
> > > 
> > > 
> > > can someone give me the kernel version for the corsola shim i need to build my module against that and not the latest recovery kernel in order to make sure i got this working correct
> > 
> > 
> > could i possibly help get that? or not
> 
> yeah just run `uname -r`

Run that where?
Edit: @leahanderson1 I ran `uname -r` in VT2 and it outputted `` 5.15.180-24494-g1e1050b313b1 ``

**Comment by jacobleclair** [comment]
you can grep partition 2. i have the command saved somewhere, ill send it
here if I find it.

**Comment by jacobleclair** [comment]
```sh
sudo dd if=/dev/sda2 2> /dev/null | grep -Eao "[0-9]+\.[0-9]+-[0-9]+-[0-9a-z]+"
```

**Comment by leahanderson1** [comment]
> sudo dd if=/dev/sda2 2> /dev/null | grep -Eao "[0-9]+\.[0-9]+-[0-9]+-[0-9a-z]+"

this actually shouldn't need sudo since all users have read access to block devices

**Comment by ryry-codr** [comment]
@leahanderson1 Sorry, but I just wanted to let you know that I’m switching back to secure/stable mode on my Chromebook because that setup feels more comfortable for me. Crostini works fine for what I need, so I won’t be able to test the kexec module. Thanks for understanding.
