### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by thespecificjhevin** [ading2210/shimboot#81]
will there be a installation? like every time i boot my chromebook i don't need the usb

**Comment by thespecificjhevin** [comment]
not any time soon but later in the future

**Comment by Tulip-0333** [comment]
??? Did you just respond to your own question

**Comment by ading2210** [comment]
You need the USB to boot Shimboot no matter what. This is a limitation of the RMA shims.

**Comment by thespecificjhevin** [comment]
alr, thank you! is there any tutorial on this? im not the best with computers lol

**Comment by ading2210** [comment]
There's a section in the README on how to do it: https://github.com/ading2210/shimboot?tab=readme-ov-file#can-i-unplug-the-usb-drive-while-using-debian

**Comment by thespecificjhevin** [comment]
thank you! sorry had to go to work for shit, but yeah can i delete chrome os or naw?

**Comment by thespecificjhevin** [comment]
also, when i do fdisk -1 it says change partition table. (im on octopus)
