### ISSUE TITLE
Install libfuse2 by default.

### ISSUE THREAD

**Issue by Tulip-0333** [ading2210/shimboot#82]
**Is your feature request related to a problem? Please describe.**
When you attempt to install an AppImage with shimboot, it tells you to install FUSE. Most distributions come with FUSE automatically, but not shimboot Debian.
**Describe the solution you'd like**
Just.. apt install libfuse2.. or something...
**Describe alternatives you've considered**
N/A
**Additional context**
![image](https://github.com/user-attachments/assets/d064ac1c-f205-42e8-98e7-2202dd1bc720)

**Comment by ading2210** [comment]
The Debian setup script now installs both libfuse2 and libfuse3-3. I confirmed that it worked by testing the Vestkop Appimage.
