### ISSUE TITLE
Ability to transfer entire drive to another

### ISSUE THREAD

**Issue by Tulip-0333** [ading2210/shimboot#85]
**Is your feature request related to a problem? Please describe.**
My drive I'm using was originally for PS3 ISOs, and I have another drive, but it's smaller. 
**Describe the solution you'd like**
There should be a command to transfer everything from one drive to another.
**Describe alternatives you've considered**
Just copying over all the partitions manually (that takes time though...) 
**Additional context**
all the ps3 isos were legal by the way

**Comment by ading2210** [comment]
What you are talking about is already easy to do with standard Linux utilities. You can mount both drives and then use either the `cp` command or `rsync` to copy all the files.
