### ISSUE TITLE
Some websites not loading in Debian 12 bookworm

### ISSUE THREAD

**Issue by Tulip-0333** [ading2210/shimboot#86]
**Describe the bug**
Some websites (like chatgpt.com and archive.org) do not load some or all of their page content. Haven't tested on other browsers yet.

**To Reproduce**
1. Be on a Dell Chromebook 3110 (dedede) (?) and use FireFox
2. Go to one of the websites stated above
3. See the results...

**Expected behavior**
The websites loading...
**Screenshots / Photos**
![image](https://github.com/user-attachments/assets/2ef649c6-858b-46fe-8869-7d3f2850c753)
chatgpt.com (cannot message, have to use Gemini, Gemini sucks.)
![image](https://github.com/user-attachments/assets/1b593c57-83aa-4f37-845e-650ea6b9f038)
archive.org

**Target Chrome OS Device (please complete the following information):**
 - dedede
 - cret or cret360 (I assume it's touch or no-touch? Mine doesn't have touch)
 - v1.2.1

**Additional context**
I know it's not the network, as it's happened on 3 separate networks, and the sites work on other machines with similar-ish specs with the same Firefox and uBlock settings.. It seems to do with the Content Security Policy? It's weird.

Also side thing does anyone know how to open the Whisker Menu with the search key I can't find out how

**Comment by ading2210** [comment]
This is a problem with your browser, not shimboot.
