### ISSUE TITLE
I am facing the exact same issue with my lenovo 300e gen3 chromebook (zork,vilboz360).

### ISSUE THREAD

**Issue by karaage-2** [ading2210/shimboot#87]
I am facing the exact same issue with my lenovo 300e gen3 chromebook (zork,vilboz360).

I ran "fdisk -l" from the shimboot shell(the option "s") with and without the sd card.

The shimboot usb(working fine with gnome) that i used to run fdisk was mounted at /dev/sda.
Without the sd card it shows that there is a device at /dev/mmcblk1 which should be the eMMC storage of the chromebook.
With the sd card it shows that there is another disk at /dev/mmcblk0 which should be the sd card.

I am very new and I don't even really know how linux usually boots but mmcblk1 should be the usual place where sd cards are 
mounted so maybe shimboot or smth else is trying to boot linux from our emmc storages.In that case I guess we just need to rewrite mmcblk1 to mmcblk0.

Maybe this bug won't be fixed by vk6 but I will leave this info here for people who is enough knowledged and trying to use shimboot on a lenovo chromebook.

_Originally posted by @karaage-2 in https://github.com/ading2210/shimboot/issues/44#issuecomment-2365158417_

**Comment by ading2210** [comment]
If mmcblk0 and mmcblk1 are swapped, it does not mean anything. 

Again, if booting from the SD card does not work, there is no way to fix it.
