### ISSUE TITLE
Every time i try to run the /.build.sh i get the same error 

### ISSUE THREAD

**Issue by thespecificjhevin** [ading2210/shimboot#89]
root@gaming-virtualbox:/home/gaming/Desktop/shimboot-main# ./build.sh /home/gaming/Desktop/shimboot-main/zoutput.img /home/gaming/Desktop/shimboot-main/rootfs arch=arm name=4b6e7881-70a0-45ff-b9b2-778d49ee8555
reading the shim image
copying the shim kernel
losetup: /home/gaming/Desktop/shimboot-main/rootfs: failed to set up loop device: Is a directory
dd: failed to open '/dev/loop6p2': No such file or directory
root@gaming-virtualbox:/home/gaming/Desktop/shimboot-main#

**Comment by ading2210** [comment]
Did you download the repository as a zip file?

Also, why did you delete the issue template that asked for things like system information?

**Comment by ading2210** [comment]
Also you are invoking the build scripts wrong. Please read the instructions again.

**Comment by thespecificjhevin** [comment]
mb, like i said im bad at this. ill go re read them. and yes i did download as a zip

**Comment by ading2210** [comment]
If you downloaded it as a zip file the permissions are messed up and it will not work. You did not follow the instructions correctly.
