### ISSUE TITLE
Google play store not working on 128 can't down grade

### ISSUE THREAD

**Issue by Dominicis1** [ading2210/shimboot#90]
When I boot into the chrome os and try to use play store on version 128 it doesn't work but when I do it on another computer on version 116 its able to open and work but I can't down grade so idk if its supposed to be like that but ya would like a little help

**Comment by Tulip-0333** [comment]
Have you tried resetting the partition? Are you signed in with a lone (non-child, non-managed) Google account?

**Comment by ading2210** [comment]
This is a duplicate of #51.

**Comment by Dominicis1** [comment]
figured out how to downgrade and make it work

**Comment by Noob0dooN** [comment]
@Dominicis1 But how did you do it?
