### ISSUE TITLE
Request: Could someone compile a Debian Stable KDE Shimboot for me?

### ISSUE THREAD

**Issue by breadcrumbsgames** [ading2210/shimboot#91]
Could someone please compile a Debian KDE ShimBoot .BIN file for me? My board type is octopus. My friends want a KDE desktop on their Chromebooks, and I just don't have the time to do it. Thank you so much, and thank you, Devs, for doing what you are doing.
If you don't know how to do this, just follow these steps:
Clone the ShimBoot repo and cd into it.
Run `sudo ./build_complete.sh octopus desktop=kde` to download the required data and build the disk image.

**Comment by ading2210** [comment]
You can fork this repository and edit the following line in the Github Actions workflow to make it build a KDE image instead:

https://github.com/ading2210/shimboot/blob/0cce802d4a16c7048d2383a83428834eefda72f5/.github/workflows/build-image.yaml#L32

Then just wait for the Github Actions workflow to complete and download the resulting artifact.

**Comment by funkymokey** [comment]
@ading2210, what exactly do I replace in this line?

**Comment by Raf128** [comment]
replace ${{ matrix board }} with your board options I assume.

**Comment by ading2210** [comment]
Add `desktop=kde` to the end of that line.

**Comment by funkymokey** [comment]
Thanks!!
