### ISSUE TITLE
No valid image detected

### ISSUE THREAD

**Issue by kmzheng01** [ading2210/shimboot#92]
I used one of the prebuilt images but when I try to use it, it says that there is no valid image detected. I followed the instructions on the sh1mmer website to run it but it still has the same error message. It there anyway to fix it or is it just a problem with my chromebook?

**Comment by Tulip-0333** [comment]
use developer mode (Ctrl+D or press the button)

**Comment by kmzheng01** [comment]
> use developer mode (Ctrl+D or press the button)

I used the instructions on sh1mmer website because my chromebook was blocked. It said to press control d and than go back into recovery mode, still didn't work

**Comment by GoudyuBad** [comment]
you do esc+refresh+power then ctrl+d then enter then esc+refresh+power again then plug it in

**Comment by ading2210** [comment]
What is the board name for your chromebook and when was it manufactured? Devices made after 2023 prevent modified shims from booting.

**Comment by kmzheng01** [comment]
> What is the board name for your chromebook and when was it manufactured? Devices made after 2023 prevent modified shims from booting.

mine is i think nissa

**Comment by kmzheng01** [comment]
> you do esc+refresh+power then ctrl+d then enter then esc+refresh+power again then plug it in

tried that but it didn't work

**Comment by henryruss2** [comment]
Same for me.

**Comment by certifiedfoolio** [comment]
@ading2210 doesnt work for me either (nissa, probably rolled keys for me since nissa image wont work), is there any possible workaround?

**Comment by OtterCodes101** [comment]
not unless you somehow found a shim with the new keys

**Comment by Fighterhen63** [comment]
@kmzheng01 @certifiedfoolio  Can you tell me your guys chromebook model. (Look at the bottom of you chromebook and somewhere under there should be a model name)

**Comment by certifiedfoolio** [comment]
> @kmzheng01 @certifiedfoolio Can you tell me your guys chromebook model. (Look at the bottom of you chromebook and somewhere under there should be a model name)

it doesn't matter, my Chromebooks keys are rolled meaning shims wont work, but its an Acer 511

**Comment by Fighterhen63** [comment]
> > @kmzheng01 @certifiedfoolio Can you tell me your guys chromebook model. (Look at the bottom of you chromebook and somewhere under there should be a model name)
> 
> it doesn't matter, my Chromebooks keys are rolled meaning shims wont work, but its an Acer 511

Well hold on a minute thats the exact one I have. Whats your chrome version?

**Comment by OtterCodes101** [comment]
This is impossible to fix unless you find an updated shim with the new keys.

**Comment by schoolaccountcolon3** [comment]
So its impossible to use shimboot if you have a 2024 chromebook?

**Comment by OtterCodes101** [comment]
yeah

**Comment by crashy102** [comment]
i have same issue with dedede, and ik my chromebook is old enough cuz the school never buys new ones lol

**Comment by ading2210** [comment]
Booting modified shims (and thus shimboot as a whole) is patched on Chromebooks manufactured after 2023. This is not a fixable issue.
