### ISSUE TITLE
Steam Error: Couldn't switch to requested monitor resolution

### ISSUE THREAD

**Issue by GoudyuBad** [ading2210/shimboot#93]
**Describe the bug**
When I am trying to play ULTRAKILL on Steam, it always pops up with a window saying this:
Couldn't switch to requested monitor resolution
Details:
Switching to resolution 1366x768 failed
Screen: DX11 could not switch resolution (1366x768 fs=1 hz=0)

I have tried using custom launch options and changing my resolution but none of it is working. I know this is like a Steam issue but I don't know where else to ask it since its kind of weird.

**To Reproduce**
1. Play ULTRAKILL on Steam on Proton 5.13
2. Wait for it to load
3. It shows error message along with a black fullscreen window that isn't shown, presumably ULTRAKILL, but didn't work because of the error

**Expected behavior**
I expected it to work if I changed some launch options or whatnot. Also, I have tried this on other versions of Proton and for those the error doesn't show up at all.

**Screenshots / Photos**
![image](https://github.com/user-attachments/assets/84d6698b-8b38-48cf-8604-5f187bf18b79)

**Target Chrome OS Device (please complete the following information):**
 - Board Name: octopus
 - Device Name: bobba
 - Shimboot version: v1.2.1

**Comment by ading2210** [comment]
Are you able to force the game to run in a windowed mode using launch arguments? That might fix this error.

Either way, this isn't a bug specific to Shimboot.
