### ISSUE TITLE
Errors when run in debian docker container :( i cant build my dream dedede debian sid kde image

### ISSUE THREAD

**Issue by TheKidThatCodes** [ading2210/shimboot#97]
**Describe the bug**

**To Reproduce**
debian 12 slim arm container
errors:
```
creating bind mounts for chroot
mount: /home/user/shimboot/data/rootfs_dedede/proc: permission denied.
       dmesg(1) may have more information after failed mount system call.
umount: /home/user/shimboot/data/rootfs_dedede/proc: must be superuser to unmount.
```

**Expected behavior**
it builds my image
**Screenshots / Photos**
If applicable, add screenshots or photos to help explain your problem.

If you are reporting an issue with the build process, please run the scripts in debug mode by putting `DEBUG=1` before the build commmand, like `sudo DEBUG=1 ./build_complete.sh`.

**Target Chrome OS Device (please complete the following information):**
i dont think this required because of where problem is

**Build Device (please complete the following information):**
 - Docker Host OS: MacOS Sequoia 15.0
 - Container Image: debian/12-slim (or smth like that)

**Additional context**
:(
heheh linux school chromebook dell 3110, (btw where do i get new bios for it?)

**Comment by ading2210** [comment]
Docker in MacOS is not supported for building shimboot. You need a real Linux system or a full virtual machine.

**Comment by ading2210** [comment]
Also, I don't own any MacOS devices so I wouldn't be able to fix this anyways.
